### ISSUE TITLE
Security Error -Phishing attack ahead

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#1]
We got this security alert error when accessing the URL www.kumulsoftfixedassets.com refer attached image. We had to click the 'you may visit the infected site' to open up
![image](https://cloud.githubusercontent.com/assets/10192106/8918986/47b155d2-34ff-11e5-88f1-3c424d6e22bb.png)

**Comment by agilecube** [comment]
We dont get this error. Can you please let us know which browser you are testing ?

**Comment by mnarewec** [comment]
Its only with Chrome. I manage to get on successfully with IE and FF

 

Cheers!

 

Marsh Narewec

Kumulsoft

**Comment by mnarewec** [comment]
This is closed because we are hosting locally first.
