### ISSUE TITLE
System Setup >> User Define Codes. Duplicate Use Define Types

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#100]
1. Asset Condition
![image](https://cloud.githubusercontent.com/assets/10192106/10569136/13fb7522-7665-11e5-9edd-a5b7cf4324ab.png)

2. BuildingUnitTYpes - One should **BuildingTypes** and **BuildingUnitTypes**
![image](https://cloud.githubusercontent.com/assets/10192106/10569168/7aad01b4-7665-11e5-88ac-a5218f16e3a7.png)

**Comment by agilecubeteam** [comment]
@mnarewec 
It's Db changes. You can clean up your DB for such duplicate values.

**Comment by mnarewec** [comment]
@agilecubeteam, I can do that at DB level but I am worried your team might had code it in Code and it will 'break' the application.

**Comment by agilecubeteam** [comment]
@mnarewec 
Run following script to remove duplicate values

Update MstUserDefineCode set UserDefineTypeId=6 where UserDefineCodeId=15
Delete from MstUserDefineType where UserDefineTypeId=17
Delete from MstUserDefineType where UserDefineTypeId=36

**Comment by mnarewec** [comment]
This issue is resolved.
