### ISSUE TITLE
Land and Building Business Rule for PAMS not Implemented **URGENT**

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#103]
As PAMS, before a Building record is created it must have its related ** land information**. This rule is not transferred here.

1. The Land Information is created first using the Land Registry Page
2. When building information is created, the Land number (Asset Parent Number) is selected during Build record creation to pick the Land information.

Refer the image below for clarity

![image](https://cloud.githubusercontent.com/assets/10192106/10594162/958a24b4-770d-11e5-93ac-9fc2edeb3a42.png)

**Comment by agilecubeteam** [comment]
@mnarewec 

Run below script in Db:
alter table [dbo].[MstAsset]
Add  LandId decimal(18,0)

**Comment by mnarewec** [comment]
This is resolved. Thanks but more work still to do with the fields placement.
