### ISSUE TITLE
Land Registry Fields Mapping

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#104]
I believe we have come up with the Land Registry Fields on of our prior discussion. I have just stating it down there for your adjustment to the Land Registry Details Page

1. Asset Number (Land Number)
2. Asset Category
3. Description

5. Division
6. Section
7. Centre
8. Suburb
9. Street  

10. Section
11. Allotment
12. Ownership - OWN /OTHERS
13. Land Lord - Do not show this field if ownership is OWN

**(If Ownership is OWN then show the following fields on the registry details page)**
9. Portion
14. Volume
15.Folio
16. Latitude
17. Longitude
18. Land Value
19. Land Area
20. Value of Improvements (Read Only - Total of all Buildings Acquired Cost)
21. State Lease Grant Date
22. State Lease Expiry Date
23. State Lease Title Doc (Document)
34. Map (Picture)

**Comment by agilecubeteam** [comment]
Run this Query:
delete FROM [fams].[dbo].[MapColumn] where [ModuleName ]='Land' and FormType='Detail'

After 1st query is executed successfully, run following query:

 INSERT INTO [fams].[dbo].[MapColumn] ([ModuleName],[ColumnName],[FormType])
VALUES ('Land','AssetNumber', 'Detail'),
('Land','CenterId', 'Detail')	
('Land','CategoryId', 'Detail'),
('Land','Description', 'Detail'),
('Land','Ownership', 'Detail'),
('Land','SectionId', 'Detail'),
('Land','Street', 'Detail'),	
('Land','Remarks', 'Detail'),
('Land','Volume', 'Detail'),
('Land','Folio', 'Detail'),
('Land','Latitude', 'Detail'),
('Land','Longitude', 'Detail'),
('Land','LandValue', 'Detail'),
('Land','LandArea', 'Detail'),
('Land','Section', 'Detail'),
('Land','Allotment', 'Detail'),
('Land','PurchaseReference', 'Detail'),
('Land','DivisionId', 'Detail'),
('Land','Suburb', 'Detail'),
('Land','LeasedAgreementDetails', 'Detail'),
('Land','LeaseAgreementDoc', 'Detail'),
('Land','StateLeaseGrantDate', 'Detail'),
('Land','StateLeaseExpiryDate', 'Detail'),
('Land','StateLeaseTitleDoc', 'Detail')
('Land','Picture', 'Detail')

**Comment by mnarewec** [comment]
Still having issues after executing the script
1. Centre is missing. Centre and Suburd should be cascading in this instance
2. Division is not showing any drop down list and so as Section

**Comment by agilecubeteam** [comment]
@mnarewec 
Please Run this query in db 
INSERT INTO [dbo].MapColumn
VALUES ('Land','LandLordId','Detail'),
 ('Land','Portion','Detail'),
 ('Land','ValueofImprovements', 'Detail')

**Comment by mnarewec** [comment]
The field mapping is solved.
