### ISSUE TITLE
Building Registry Fields Mapping Mapping

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#105]
I believe we have discuss the Building Fields but I want us to re-fresh the information gain here. Following are the data entry fields of Building Registry Page

1. Building Number (Asset Number)
2. Building Type (Asset Category)
3. Description
4. Property Level
5. Number of Building Units (Automatically create the Building Unit Records)

6. Acquired Date
7. Acquired Cost
8. Purchase Reference
9. Remarks

10. Division
11. Section
12. Centre
13. Suburb

14.  Land Number

If land ownership is 'OTHERS' then show
15. Lease Agreement Details
16. Lease Agreement Doc

17. Show the Land details (Section,Lot, Allotment, Land value etc) - This will be read only fields and fields displayed will be depended on the land Ownership.

**Comment by agilecubeteam** [comment]
Run this Query:
 delete FROM [fams].[dbo].[MapColumn] where [ModuleName ]='Building' and FormType='Detail'

After 1st query is executed successfully, run following query:

INSERT INTO [fams].[dbo].[MapColumn] ([ModuleName],[ColumnName],[FormType])
VALUES ('Building','AssetNumber', 'Detail'),
('Building','PropertyLevel', 'Detail'),	
('Building','CategoryId', 'Detail'),
('Building','Description', 'Detail'),
('Building','NoOfBuildingUnit', 'Detail'),
('Building','AcquiredDate', 'Detail'),
('Building','AcquiredCost', 'Detail'),
('Building','Remarks', 'Detail'),
('Building','Folio', 'Detail'),
('Building','Latitude', 'Detail'),
('Building','Longitude', 'Detail'),
('Building','LandValue', 'Detail'),
('Building','LandArea', 'Detail'),
('Building','Section', 'Detail'),
('Building','Allotment', 'Detail'),
('Building','PurchaseReference', 'Detail'),
('Building','DivisionId', 'Detail'),
('Building','CenterId', 'Detail'),
('Building','Suburb', 'Detail'),
('Building','LeasedAgreementDetails', 'Detail'),
('Building','LeaseAgreementDoc', 'Detail')

**Comment by agilecubeteam** [comment]
sorry for above query:

Run this Query:
delete FROM [fams].[dbo].[MapColumn] where [ModuleName ]='Building' and FormType='Detail'

After 1st query is executed successfully, run following query:

 INSERT INTO [fams].[dbo].[MapColumn] ([ModuleName],[ColumnName],[FormType])
VALUES ('Building','AssetNumber', 'Detail'),
('Building','PropertyLevel', 'Detail'),	
('Building','CategoryId', 'Detail'),
('Building','Description', 'Detail'),
('Building','NoOfBuildingUnit', 'Detail'),
('Building','AcquiredDate', 'Detail'),
('Building','AcquiredCost', 'Detail'),	
('Building','Remarks', 'Detail'),
('Building','Folio', 'Detail'),
('Building','Latitude', 'Detail'),
('Building','Longitude', 'Detail'),
('Building','LandValue', 'Detail'),
('Building','LandArea', 'Detail'),
('Building','Section', 'Detail'),
('Building','Allotment', 'Detail'),
('Building','PurchaseReference', 'Detail'),
('Building','DivisionId', 'Detail'),
('Building','CenterId', 'Detail'),
('Building','Suburb', 'Detail'),
('Building','LeasedAgreementDetails', 'Detail'),
('Building','LeaseAgreementDoc', 'Detail')

**Comment by mnarewec** [comment]
The following fields are missing from the Building Registry page after executing the script you provided.
1. Number of Building Units
2. Acquired Date
3. Acquired Cost
4. Section (Business Unit section)
6. Centre
7. Suburb
8. Land Number (Asset Parent Number)
9. Lease Agreement Doc
10. Purchase Reference

**Comment by agilecubeteam** [comment]
Asset Type is parent for Asset Category so,we need  Asset type in Building Registry , Land Registry.

**Comment by agilecubeteam** [comment]
@mnarewec 
Please Run this query in db 
INSERT INTO [dbo].MapColumn
VALUES  ('Building','SectionId', 'Detail')

**Comment by mnarewec** [comment]
@agilecubeteam 
1. Do not show editable Sec & Lot fields. These are read only fields and are shown when a land number is selected.
2.Land Number should be filtered by the Centre and Suburb

**Comment by mnarewec** [comment]
This issue will be closed because it is addressed in #121
