### ISSUE TITLE
Fleet Management >> Main menu page Link not working for some menu items and some items are missing

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#108]
Following are the menu items link not working. They are showing the User Management page. Some items are also missing.
1. Vehicle Registry
2. Vehicle Disposal
3. Dashboard
4. Fuel Management sub-menu is missing
6. Incident is missing

![image](https://cloud.githubusercontent.com/assets/10192106/10595510/4c8ea884-771c-11e5-9318-4cc4dac6ebbf.png)

**Comment by agilecubeteam** [comment]
Issue1: Vehicle Registry

Run following query in db

UPDATE [fams].[dbo].[Permission] SET [State]='app.asset({id:77})'
Where [PermissionName]= 'Vehicle Registry'

Issue 2 : Vehicle Disposal

Run following query in db

UPDATE [fams].[dbo].[Permission] SET [State]='app.asset-disposal'
Where [PermissionName]= 'Vehicle Disposal'

Issue4:
run following query in db:

SELECT *
  FROM [fams].[dbo].[Permission] where [PermissionName]= 'Fleet Management' 

if the data is not present , enter following data in Permission table where,

Data 1:

PermissionName = Fleet Management,
State=Fleet Management,
SequenceId = 4

Data 2:
PermissionName = Fleet,
State = Fleet,
ParentId = PermissionId of Data 1
SequenceId = 1

Data 3:
PermissionName = Incidents,
State = app.incident,
ParentId = PermissionId of Data 2
SequenceId = 3

Data 4:
PermissionName = Allocation,
State = app.asset-allocation,
ParentId = PermissionId of Data 2
SequenceId = 2


Data 5:
PermissionName = Vehicle Dashboard,
State = app.vehicle-dashboard,
ParentId = PermissionId of Data 2
SequenceId = 1

**Comment by mnarewec** [comment]
@agilecubeteam , refer my comments above in bold

**Comment by agilecubeteam** [comment]
@mnarewec 
Can you please send me data after running following script on your machine?

select * from [dbo].[Permission]

**Comment by mnarewec** [comment]
here is the link to the data

https://drive.google.com/file/d/0B9T2hcAcxJgLQnZLZFBadzNLRWs/view?usp=sharing

**Comment by agilecubeteam** [comment]
@mnarewec 

Please Execute the following query and send me the result
SELECT*
  FROM [fams].[dbo].[MstAssetType]

**Comment by agilecubeteam** [comment]
@mnarewec
To make Fuel Management available in menu , Please select the Fuel Module in
Security -> Manage Roles ->Administrator(Manage Permission)

**Comment by mnarewec** [comment]
This is closed but will raise other issue again for two menu items
