### ISSUE TITLE
Asset Registry >> Vehicle Registry page. correct the 

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#110]
1. Serial Number should be label as 'Engine Number'
2. Part Number should be label as 'Chassis Number'
3. Populate the empty space between current physical location & vendor fields (put them onto same row to save space etc)

![image](https://cloud.githubusercontent.com/assets/10192106/10595721/ec47f05e-771e-11e5-9ee0-5fc9bfd6f669.png)

**Comment by agilecubeteam** [comment]
@mnarewec 
1 & 2 are fixed
for 3 it will be covered in #86
Hence marking as Fixed

**Comment by mnarewec** [comment]
ok consider this closed
