### ISSUE TITLE
Fleet Management : Two menus not working or showing the 'User Management Page'

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#118]
Refer image below i.e. Allocation and Compliance Dashboard

![image](https://cloud.githubusercontent.com/assets/10192106/10733222/85848f28-7c49-11e5-914b-5cf97d70d3db.png)

**Comment by agilecubeteam** [comment]
Run following script :

Update Permission set State='app.dashboard({id:4})' where PermissionId=39
Update Permission set State='app.vehicle-allocation' where PermissionId=28

dashboard is not implemented, so it might be give error

**Comment by mnarewec** [comment]
This issue is resolved for now.
