### ISSUE TITLE
Manage Land >> Details Page. Fields placememt

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#119]
As per your request. This is the fields placement for Land Registry detail page

![image](https://cloud.githubusercontent.com/assets/10192106/10747865/e9fc3288-7ca5-11e5-88f2-7b885cd202ca.png)

**Comment by agilecubeteam** [comment]
@mnarewec 

Please Run this script in DB
  update [dbo].[MapColumn] set ColumnName = 'SectionName'
  where MapColumnId =1447

  delete from [dbo].[MapColumn] where MapColumnId = 1442

**Comment by mnarewec** [comment]
@agilecubeteam , what will be the outcome of this script. will it achieve the desired outcome shown in the image above?

**Comment by agilecubeteam** [comment]
@mnarewec 
No, it won't fix the issue.

**Comment by agilecubeteam** [comment]
https://github.com/kumulsoft/Fixed-Assets/issues/104 

you have asked hide picture in this above  issue. what will be the next

**Comment by mnarewec** [comment]
@agilecubeteam , move the picture image down to where the fields that will be shown if ownership is OWN

**Comment by mnarewec** [comment]
This issue is resolved.
