### ISSUE TITLE
System Setup >> Fleet >> Manage Vehicle Model. Error

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#123]
There is a runtime error when opening/ accessing that page. Make should now be replaced by 'Manufacturer' i.e. from the UDC.

![image](https://cloud.githubusercontent.com/assets/10192106/10749199/7074de16-7cb3-11e5-83e1-ec263ab2915d.png)

**Comment by agilecubeteam** [comment]
@mnarewec It' old screen. it's not required at all. We can remove it from menu. 
It's been replaced by Manufacturer in UDC

**Comment by mnarewec** [comment]
yes you correct. Please remove from menu

**Comment by mnarewec** [comment]
Its still there. Not removed.

**Comment by mnarewec** [comment]
Ok removed now. thanks
