### ISSUE TITLE
Asset Administration >> Asset Allocation>> Detail Page :: Unable to save because of staff

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#130]
Please refer image below and the issues identified on the image.

![image](https://cloud.githubusercontent.com/assets/10192106/10782778/c53d94ba-7d9e-11e5-8e60-a090d5b5ec65.png)

**Comment by agilecubeteam** [comment]
1. which date format you want ?
2. To allocate  asset to Staff , Section Of All Assets should be same .if all Asset's Section is Same then staff list is filtered by that section .if no staff found for same section  so staff list is  empty.
  and in staff list we are binding StaffId and EmployeeGrade ,and in your data all EmployeeGrade is empty

**Comment by mnarewec** [comment]
1. Date Format : YYYY-MM-DD
2. Why Binding staffid with EmployeeGrade, what significant it makes?

**Comment by agilecubeteam** [comment]
as per the old code , now we have replaced with SatffName

**Comment by mnarewec** [comment]
This has been resolved.
