### ISSUE TITLE
Building Management >>Set up Building Units :: Grid Page re-arrangemet & Filtration

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#134]
1. Include Filtration
2.Include Search
3. Re-arrange columns as per order (numbers) shown on image.
![image](https://cloud.githubusercontent.com/assets/10192106/10789059/eb179546-7dc6-11e5-90b1-ebfcf25c7693.png)

**Comment by mnarewec** [comment]
@agilecubeteam , as per #139 , please disregard the above image, and consider the image and details below

![image](https://cloud.githubusercontent.com/assets/10192106/10837358/5de547d8-7f04-11e5-9962-25fcc8e7790f.png)

The following fields should be shown on the grid in the following order.
1. Building Number
2. Level
3. Unit Number
4. Unit Type
6. Centre
7. Suburb
8. Status (Tenancy Status)
9. Tenant (if status=occupied)
10. Dependents (if status=occupied Nbr of Dependents + Names of Dependents)
12. Remarks

**Comment by agilecubeteam** [comment]
@mnarewec  
According your  image fields  and Describe fields are different so, Please verify and Update.

**Comment by mnarewec** [comment]
@agilecubeteam , Disregard the image. ONLY consider the fields below

Building Number
2. Description (Building Description)
3. Type (Building Type)
2. Level
3. Unit (Unit Number)
4. Unit Type
6. Condition (Unit Condition)
8. Status (Tenancy Status)
9. Tenant (if status=occupied)
10. Dependents (if status=occupied Nbr of Dependents + Names of Dependents)
12. Remarks

**Comment by mnarewec** [comment]
1. In the detail page Unit Condition is not captured. Remove these two highlighted fields and replace them with Condition.

![image](https://cloud.githubusercontent.com/assets/10192106/11433554/322d9336-950a-11e5-923e-9137162a0cce.png)


2. Remove Field 'Remark' from grid to give more space.

**Comment by mnarewec** [comment]
@agilecubeteam , Building Units data not showing on the grid so difficult to accept. Please check .

**Comment by mnarewec** [comment]
Core issues raised here are resolved but some other issues are still outstanding and are raised in #262
