### ISSUE TITLE
Building Management >> Manage Buildings. Some records missing when entered using Manage Buildings in Asset Registry 

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#138]
**Missing data in *Manage Building* in Building Management**
![image](https://cloud.githubusercontent.com/assets/10192106/10835905/1dbdb94e-7ef3-11e5-9937-b449c1eee615.png)

** Data present in *Manage Building* in Asset Registry**

![image](https://cloud.githubusercontent.com/assets/10192106/10835923/67bc0d8e-7ef3-11e5-8836-7a1aa57cb052.png)

**Comment by agilecubeteam** [comment]
In Manage Building in Asset Registry showing Asset list where AssetType is Building and in  Manage Building in Building Management showing Asset where SystemModule is Building .
so it is different

**Comment by mnarewec** [comment]
@agilecubetea, If asset type module is defined as Building then it should display in Building Management same as Asset Registry. I will raise an issue to remove asset types menu define as Fleet, Land, Building from the Asset Registry Main menu

![image](https://cloud.githubusercontent.com/assets/10192106/10856222/f50f90d6-7f91-11e5-9986-0f47eb894bf3.png)

**Comment by mnarewec** [comment]
This issue is closed.
