### ISSUE TITLE
Building Management >>Setup Building Units >> Use same menu and Grid to setup units and allocate/de-allocate/modify allocation information

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#139]
We would like to Use same menu and Grid to setup building units and allocate/de-allocate/modify allocation information.

**SETUP BUILDING UNIT GRID VIEW CHANGES**
1. Hide Allocate Build Unit Menu and Rename ' Setup Building Units' to **Setup and allocate Building Units**

![image](https://cloud.githubusercontent.com/assets/10192106/10837131/99efd5d4-7f01-11e5-9faa-9a93a8b7527a.png)

2.When a Building Unit is occupied rename the 'De-allocate' Button label to 'De-allocate/Modify'. 
![image](https://cloud.githubusercontent.com/assets/10192106/10837264/05957a04-7f03-11e5-8d1f-a050343af3b7.png)

**BUILDING UNIT ALLOCATION DETAIL PAGE CHANGES**
3.When De-allocating or Modify Building Unit  Allocation information,  when a a date is set against **Date moved out** field, then that unit is de-allocated other-wise other allocation information will updated.

4.When saved/cancel button pressed, then it return to the **Setup and Allocate Building Units** grid page.

**Comment by agilecubeteam** [comment]
@mnarewec  
As per #136 you ask to change Manage Accomodation Building Unit (Allocation Building Unit )Grid But Now you are saying allocation building unit  link Remove  So, what will be the next ?

**Comment by mnarewec** [comment]
@agilecubeteam , I will close #136

**Comment by mnarewec** [comment]
@agilecubeteam 
After allocating a buillding unit it returns to the old Building Unit allocation page and not the current one Setup and allocate building units. Make sure that after allocating it must re-direct to same page again

**Comment by mnarewec** [comment]
Unable to allocated vacant units because it is not listing them for selected buildings.

**Comment by mnarewec** [comment]
This has been resolved. Thanks.
