### ISSUE TITLE
Asset Numbering Issue - General Assets and Motor Vehicles (excluding Land and Building)

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#141]
The current format is AA.YY-DDD.SSSS-NNNN 
where 
AA=Asset Type
YY=Acquired Year
SSSS=Section Code
NNNN=Asset Automatic Id (it should be filled with 0 i.e. left-padded with 0).

NNNN=left padded with zero. Currently its not doing left padded with 0

**Comment by agilecubeteam** [comment]
@mnarewec 
 Currently we are auto generating AssetNumber for All Asset excluding General Assets 
in following format
TT-YY.DIV-SSS-NNNN.
and now you are saying that  Asset Numbering for General Assets and  Vehicles 
so what about Building and Land ?

**Comment by mnarewec** [comment]
@agilecubeteam 

1. General Assets and Motor Vehicle = TT.YY-SSS-NNNN, yes you are generating correctly but you are not left pading with zero. Refer image attached.

![image](https://cloud.githubusercontent.com/assets/10192106/10856082/f034166e-7f90-11e5-89bb-77690a4e27c9.png)

2. Land and Building = TT.YY-CCC-NNNN,  where CCC=Centre Code

**Comment by mnarewec** [comment]
@agilecubeteam, team my apologies I have been incorrectly advising. It should be in this format
AA.YY-DDD.SSSS-NNNN 
where 
AA=Asset Type
YY=Acquired Year
DDD=Division Code
SSSS=Section Code
NNNN=Asset Automatic Id (it should be filled with 0 i.e. left-padded with 0).

NNNN=left padded with zero. Currently its not doing left padded with 0

![image](https://cloud.githubusercontent.com/assets/10192106/10995444/9893997e-84c8-11e5-992a-b6774cb43461.png)

the asset number should be **WG.15-ENF.1110-0434**

**Comment by mnarewec** [comment]
This is implemeted.
