### ISSUE TITLE
Data Grids (Browse) Page - Format and re-arrange presentation to be like Billing System

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#151]
Grids here are ok, Just
1. Arrange column headings neatly,
2. Re-arrange columns so that fit neatly, at much as possible we try to make sure fields do not wrap
3. Differentiate between rows by color all even number rows.

**Comment by agilecubeteam** [comment]
Only point 3 needs to be done as per discussion on chat

**Comment by mnarewec** [comment]
@agilecubeteam, I like earlier columns, as discussed I just want the rows to be colored differently. In the current release
1.  Remove the column lines
2. Use this color code #F6CECE for the even rows and will see
3. The action items should be are like previous i.e. if wrapping then two actions above and two below refer image

**Comment by mnarewec** [comment]
This enhancement has been implemented.
