### ISSUE TITLE
Asset Administration >> Change Asset Maintenance to Asset Transaction

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#153]
1. Rename Menu/permissions/labels/headers from Asset Maintenance to *Asset Transactions*
1. Rename db table MstAssetMaintenance to MstAssetTransaction

2. RENAME FIELDS
(a) Rename AssetMaintenanceId to *AssetTranId*
(b) Rename MaintenanceDate to *TranDate*
(c) Rename MaintenanceDetails to *TranDetails*
(d) Rename MaintenanceType to *TranType* 
(e) Rename MaintenanceCost to *TranAmount*

3. ADD NEW FIELDS
a. asset type
a. Cheque Number
b. GL Account 
c. Account Source, 
d. Section, 
e. AssetValue (Currency, Read Only)
f. Other Reference
h. Entry Method (IMPORTED=Entered thru thru Data Import Utility, MANUAL=Entered Using the Interface)
i. Posting Status

4. USER DEFINE CODE CHANGE 
a. Rename UDC Type 'AssetMaintanceType' to 'AsstTransactionType'. The UDC Codes should be system defined and (hard coded) and should have following codes
b. PURCHASE - Normal Purchase of an Asset. For this type of transaction TransAmount=AssetValue.
c. MAINTENANCE - Normal Asset Maintenance.For this type of transaction AssetValue=0
d. CONSTRUCTION - Development of New Asset.For this type of transaction TransAmount=AssetValue.
e. IMPROVEMENT - Doing Improvements to existing Asset. For this type of transaction TransAmount=AssetValue.

4. MODIFY DETAILS PAGE
a. reflect the above changes and 
b. also capture the new fields.
c.  Also include in the details page description/Category/Custodian of the asset when it is selected to provide more information about the asset.
d. Also include ONLY Section centre (not location) to quickly filter out Asset Number DDL
e. When Transaction Type is PURCHASE asset number is *mandatory not required*, When Transaction Type is MAINTENANCE, Asset Number is *Mandatory required*, when Transaction Type is CONSTRUCTION Asset Number is *not mandatory*, when Trans Type is IMPROVEMENT asset number is *mandatory required*

7. MODIFY GRID PAGE
(A).  Show the following fields: asset number, asset description, Trans Date (YYYY-MM-DD), Trans Type, Tran Details, Supplier, Trans Amount, AssetValue, Status (Posting Status)
(B). Filter Grid by Division, Section, Centre,Transaction Types, Entry Method, Posting Status
(C). Show button to select single or multiple transaction to POST unposted transactions.
(D). Show Add button to add new transactions.
(E). User can ONLY Edit/Modify *unposted* transactions FOR ONLY MANUAL RECORDS

8. BUSINESS RULES WHEN POSTING
(a). PURCHASE transaction - Creates new Asset Master Record. The Asset Value equates to the MstAsset.AcquiredCost  and MstAsset.CurrentValue. Also update the data import table with new Asset Id if the transactions is generated using Import Utility i.e. Entry Method=Imported
(b). MAINTENANCE  - does nothing.
(c). CONSTRUCTION  - Create new Asset Master Record if asset does not exist. Otherwise updates existing record. If creates new record then Asset Value equates to the MstAsset.AcquiredCost  and MstAsset.CurrentValue and if updates the existing record then the Asset Value **increase** the MstAsset.AcquiredCost MstAsset.CurrrentValue.
(d). IMPROVEMENTS -  Only updates updates existing record. Asset Value **increase**  MstAsset.CurrentValue.

**Comment by mnarewec** [comment]
@agilecubeteam, sorry had to change PRIORITY to high because, we will use it as alternative to Data Import Utility while you were on holidays. I am under pressure, to reconcile these transactions already imported and that  functionality will save us a lot of time.

**Comment by agilecubeteam** [comment]
in this  issue business rules against the  MstAssetMaintenance not for MstAsset na ? i.e. AssetValue 
just for Confirmation

**Comment by mnarewec** [comment]
As mentioned in the Google hangout,

AssetValue in MstAssetMaintenance will affect AcquiredCost and CurrentValue in MstAsset.

**Comment by agilecubeteam** [comment]
AS Per discussion it will be in next Release

**Comment by agilecubeteam** [comment]
@mnarewec 
every Asset Maintenance(Asset Transaction)  is for specific Asset. and in Asset we have AssetType. From AssetType we can get System Module. SO do we need SystemModule as new field here ?

**Comment by agilecubeteam** [comment]
@mnarewec 
Is the posting status same as asset master status? if no , is it the dropdown ? if  yes, what data will be used in dropdown?

**Comment by mnarewec** [comment]
@agilecubeteam , No Posting Status is not the same as Asset Master Status

Posting Status is at the Asset Transaction level, its like a approval process

**Comment by mnarewec** [comment]
OK This is Asset Transactions. In this feature, its data grid will have all records created thru various other components like 'Asset Depreciation, Asset Revaluation, Asset Maintenance and Import Data Utility'

The status of these records will be unposted i.e. PostingStatus=0. User will required permission will then select these transactions and post this records, during the posting process, it will create new assets if no asset exist or update existing assets, once that is done, its Status will change to Posted i.e. PostingStatus=1

**Comment by mnarewec** [comment]
Need adjustments, refer image below
![image](https://cloud.githubusercontent.com/assets/10192106/12740319/b989210a-c9bd-11e5-86b5-0a4b344de1c0.png)

1. **Asset Type** should be moved up to be close with Section, Centre because these fields are used to filter the asset number.
2. **Section** field is duplicated
3. **Entry Type** should be default to manual (read only) if user is adding transaction using the Asset Transaction Interface
4. These fields are not showing data of the asset selected.
5. **Posting Status** should be read only because it is depended on the business rule
6. **Asset Number** should not be mandatory because NEW assets without numbers can be created.

**Comment by mnarewec** [comment]
As per our Gtalk Yesterday
1. On detail Page of Add Asset Transaction, have two radio buttons for user to select to notify whether to UPDATE an existing asset information or to Add a NEW asset information.
2. When Adding Asset Transaction, on Grid Page, user should be able to POST this transaction. This is not happening.

**Comment by mnarewec** [comment]
The core functionalities of this issue has been implemented. There are some issues arising I have raised them in separate new issues #266 ,#267 and #268 

This main issue is now considered close.
