### ISSUE TITLE
Changes to Import Utility

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#154]
**Briefly:**
Normally, an organisation will already have a ERP (Financial System) that will be in place. They will use that system to purchase assets or do maintenance or development on these assets.  When they purchase/maintain an item it must come out from a GL account. There are GL Accounts specially for assets which they should use but sometimes when monies are not in that account they use other accounts to buy or maintain assets. That is the reason why we will have to import all transactions and provide a feature/staging so user can decide which transactions they do not need to import.

The transactions (data) that we are going to import are actually generated AFTER a cheque ran (printing of cheques). These transactions are actually cheque transactions. A cheque contain one or more transaction lines. These transaction lines represent the GL Account and Section where the monies came out from to form the total cheque Amount. If monies came out from One GL Account then it will be one line for one cheque number. If monies came out from two different GL Accounts OR two different Sections then it will be two transaction lines for one cheque Number.

**Asset Transactions:**
1. One GL Account represents one Transaction line
2. A cheque number can have multiple GL Accounts which equates to multiple transaction lines
3. One transaction Line -  can mean  purchase (or maintenance,improvement or construction) of one asset or multiple assets and or including other non-assets
4. An asset can be created on multiple transactions. Two cheques can be raised to purchase (or maintenance,improvement or construction)  of an asset. First it is created singly, then it is updated.

**Raw Data or Data from the ERP System**
You already have the text file. For the benefit of readers, below is the excel image. The fields that are highlighted are to be imported.
![image](https://cloud.githubusercontent.com/assets/10192106/10862907/af66823a-8007-11e5-8bfe-7329afad2bca.png)

**Our requirements.**
![image](https://cloud.githubusercontent.com/assets/10192106/11668854/1555a7f0-9e45-11e5-9727-c117cd4b6838.png)

Basically to be able to import these transactions into the system and then base on these transactions to create new assets OR update existing asset data.
Here are the steps : 
1. Import data as it is into a database table
2. Bulk Update the Imported Transactions
3. Detail Update the Imported Transactions (Split, Merge etc)
4. Create *Asset Transactions* 

**STEP 1 - CHOOSE AND UPLOAD DATA  status=1**
Provide option for user to browse to a location on the PC to upload a CSV file

**STEP 2 - IMPORT DATA :: Status=2**
Import data as it is into a database table MstAssetImport, so user can update the imported transactions.  Following are the fields of the table

*Fields as per import file *
(a). ImportId (Auto)
(b). GL Nbr (Import file field: GE No)
(c). Cheque Date (Import file field: GE Date) - will become the Transaction Date and or Acquired date for new asset.
(s). Account Source ( part of Import file field:GE Account) - validate with existing Account Source
(d). GL Account  Code( part of Import file field:GE Account) - validate with existing GL Code
(e). Section  Code( part of Import file field:GE Account) - validate with existing section

![image](https://cloud.githubusercontent.com/assets/10192106/12742697/ed89a57c-c9d3-11e5-9e35-c033154be5df.png)

(f). Payee (Import file field: Payee) - will have to map to Vendor
(g). Detail (Import file field: Detail) - This will form the Trans Detail
(h). ChequeNumber (Import file field: Chq/Ref no)  - Cheque Number
(i). Tran Amount (Import file field: Credits-Pay) - This is the Transaction Amount

*System Fields*
(o). ErrorStatus (0=No Error, 1=Error) - Marked error if validation/Import fail
(P). Stage (1=Upload, 2=Imported, 3=Bulk Updated, 4=Detailed Updated, 5=Posted)
(q). AssetTransId - updated when Asset Transaction is created
(r). AssetId = updated when asset record created or updated.
(s). User Id - user who updated/processed records.

*Import Reference fields*
s. Import Date
t. Import Userid
t. Import Reference - User to enter this when creating a new import.

**STEP 3 - BULK UPDATE :: Status=3**

*Fields that got to be updated **before** proceeding to Stage 4*
(j). Centre - field to be update
(k). Asset Type - field to be updated
(l). Vendor - Field to be updated base on Contacts Vendors
(m). Transaction Type - Field to be update. Allowable values are (PURCHASE, MAINTENANCE, IMPROVEMENT, CONSTRUCTION,NON-ASSET)
(n). Record (NEW, EXIST)

(a). Filter records by GE Account, Payee, Amount (use Greater than or less than filter functionality)
(b). Search Detail or Cheque Number, to filter records
(c). Base on these filtered/search records i.e. a and b above, the user can do multiple selection and perform deletion of unwanted transactions.
(d). Base on these filtered/search records i.e. a and b above, the user can do multiple selection and perform updates of for the following fields  Centre, Asset Type, Vendor, Transaction Type, Asset Record - all these are mandatory for a asset record to be created or updated. 

**UI Expection**
I ideally, we want a feature when user select multiple transactions and click update, it will show fields Centre, Asset Type,Vendor, Transaction Type, Asset Record. User chose one field and select the existing data e.g. if user select Centre then it will show list of existing centres, to chose from. After selecting, user click update button, and all the multiple records are updated with same centre. The same applies to all other fields. User can ONLY update one field at a time. For a transaction line to proceed to next stage, its related fields must ALL be updated. So the status field is only updated (Status=1) when all the required fields are populated.

**Some Update Rules**
1. When Transaction Type='MAINTENANCE' the Asset Record Type Must always be 'EXIST'
2. When Transaction Type='PURCHASE' the Asset Record Type must always be 'NEW'
3. For a transaction line to proceed to next stage, its related fields must ALL be updated. So the stage field is only updated (Status=3) when all the required fields are populated.

**STEP 4 - DETAIL UPDATE :: Status=4**

fields that got to be updated **before** proceeding to Stage 5**
(j). Asset Number - if Record= EXIST
(o). Description - ONLY when Record=NEW
(l). Asset Category - ONLY when Record=NEW
(m). Asset Amount  - Required 

User can do one of the following on selected Bulk Updated (STAGE=3) transactions

1. Single Transaction  - based on one line of transaction (1 Line=1 Asset). Multiple Imported transactions can be selected and and updated. User intervention is required to enter Asset Number,Description,Asset Type,Asset Category, Asset Amount,Custodian. Ideally a pop window with selected transactions will show and only the *detail update fields* will be editable. When saving it will update the respective selected records

2. Split Transaction - can only be used on Single Transaction Line. Does not allow multiple transactions selection. Ideally, a pop up window will allow user to create multiple same transactions with the following fields Asset Number,Description,Asset Type,Asset Category, Asset Amount,Custodian editable. When saving it will delete the original transaction but create the multiple transactions with updated fields. One Rule is that the Tran Amount original transaction line must equal to the Sum of Asset Amount all new transaction lines. If move then advise user to adjust Asset Amount to Balance to Tran Amount. If Less then prompt user to adjust Tran Amount or to Create NON-ASSET type transaction automatically to balance with Tran Amount.

3. Set Status =4

**STEP 5 - CREATE ASSET TRANSACTIONS RECORDS :: Status=5**
(For Asset Transactions refer to #153 for more information)

**Steps for automatic creation**
1.These is for all Transactions that have Status =4
1. Create Related Asset Transactions base on the #153 business rules.
2. Set Status=5

**Import table mapping to Asset Transaction**
Cheque Date = Trans Date
GL Account = GL Account
Account Source = Account Source
Section=Section
Transaction Type = Transaction Type. Rules in #153 applies here too.
Detail = Tran Detail
Amount=Tran Amount and or AssetValue depending on Transaction Type Rule.
Import Reference = Other Reference.
Vendor=Vendor

** UI REQUIREMENTS **

1. Create new menu item under Asset Administration and called 'Import Asset Transactions'

2. The Data Grid Will show the contents of table MstAssetImport, Ideally show the following fields on the grid
(c). Chq Date (Cheque Date )
(s). Acc Src (Account Source) 
(d). GL Acc (GL Account)
(e). Section
(f). Payee
(g). Detail
(h). CHQ (ChequeNumber)
(i). Trn Amt (Tran Amount)
(j). Centre
(k). Type (Asset Type)
(l). Vendor
(m). Trans Type (Transaction Type)
(n). Record
(j). Asset Number
(o). Description
(l). Cat (Cat)
(m). Asset Amt (Asset Amount)
(o). Stg (Stage)

3. Do not show processed (Step=5) records.

**Comment by agilecubeteam** [comment]
@mnarewec  

In the step 4, for changes in Master Asset Registry table , there is no Centre in the table. We save Location.

**Comment by mnarewec** [comment]
@agilecubeteam , ok we map to location but it should not not be mandatory.

**Comment by agilecubeteam** [comment]
@mnarewec  
Is UserId for ImportReference is AutoIncrement or AutoGenerate ?

**Comment by mnarewec** [comment]
@agilecubeteam , userId should of the user who imported the data.

**Comment by agilecubeteam** [comment]
@mnarewec 
In System Fields, Error status and Status has to be stored in db ? Where should I use it ?

**Comment by mnarewec** [comment]
@agilecubeteam , Error Status is a boolean field that will indicate whether the imported transaction has  some errors or not. e.g. if imported 'section' cannot be found, then that flag is set on
Status should really be the stages i.e. 1=Import Data, 2=Bulk Update, 3=Detail Update.

**Comment by mnarewec** [comment]
@agilecubeteam , hopefully, this information gives the high level flow of import data.
![image](https://cloud.githubusercontent.com/assets/10192106/11649849/1f5b8a38-9dcf-11e5-8f02-fbb73253fc66.png)

**Comment by mnarewec** [comment]
@agilecubeteam , therefore disregard the requirement where you will create asset master records from imported data. Asset Master records are created or updated when Asset Transaction records are posted.

**Comment by agilecubeteam** [comment]
@mnarewec 
Asset Transaction will be created on every asset depreciated ?

**Comment by agilecubeteam** [comment]
@mnarewec 
 on every asset depreciated , the depreciated amount will be transaction amount for new transaction . is it like that?

**Comment by mnarewec** [comment]
YES, say the Asset Current Value is K10,000, and depreciation Amount is K500, when this depreciation transaction is posted, the Asset Current Value will be K9500.

**Comment by mnarewec** [comment]
Unable to test this because it came up with error. I require your assistance to test this

**Comment by mnarewec** [comment]
1. STAGE 2  (Step 2) - BULK UPDATE  -- as per above requirement. Bulk Update should happen in Stage 2. This has not been implemented as per requirement.

![image](https://cloud.githubusercontent.com/assets/10192106/12929868/e9c5515a-cfc0-11e5-853b-66e95818101d.png)

1. Acc Src - should be populated as per requirement above i.e. refer Stage 1
2. Section - Should be populated as per requirement above i.e. refer Stage 1
3. Sorting - These columns should be allowed sorting so that it will be easier for user to select records. This is to improve user experience.
4. Select All /De-Select All Check box on the header - This will allow multiple selection of records as per grid search results, at once. This is to improve user experience
5. Replace From Amt with Acc Src for search criteria
6. Replace to Amt with Section for search criteria
7. Include search button
8.ALL THE ABOVE SHOULD BE HAPPENING IN STAGE 2 as per my requirement above

**Comment by mnarewec** [comment]
Even though this requirement is completed as per expectation, I have decided to close this issue so I can create separate issues (#269,#270,#271,#273) to break this requirement into parts to give clarity to the whole process.
