### ISSUE TITLE
Reports >> Tenancy Registry Report. Changes to it

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#157]
Make the following changes
1. Remove Groupings i.e NO totals

2. Make sure it is landscape

3. Include only the following fields
a. Building Number
b. Description
c. Type (Category)
d. Unit Number
e. Centre
f. Suburb
g. Sec
h. Lot
i. Tenant - Staff Name if Occupied (otherwise use the text 'VACANT')
k. Moved In - Date moved int
l. Dep - Number of Dependents
m. Dependents - Names of Dependents

**Comment by mnarewec** [comment]
Again, this report is not showing FULL Report, it should list all the buildings in the system system and the related Building Units.

**Comment by agilecubeteam** [comment]
@mnarewec    We allow only 12 columns  so, which columns you want to hide ???
Proper Format  Purpose.

**Comment by mnarewec** [comment]
Refer my updated issue

**Comment by agilecubeteam** [comment]
@mnarewec 
updated issue is already resolved. Please check our comment regarding report format.

**Comment by mnarewec** [comment]
This is great. Thank you.
