### ISSUE TITLE
Fleet Management >> Incidents >> Details Page Issues. Difficult to save

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#167]
Unable to save because of some fields. Please re-arrange, or remove fields as per the image below
![image](https://cloud.githubusercontent.com/assets/10192106/10866934/f77613ba-8093-11e5-99be-9328a6071ca4.png)

**Comment by agilecubeteam** [comment]
@mnarewec 

In this page , Do we need Incident status ,Section , Sub-Section ?

**Comment by mnarewec** [comment]
No.

**Comment by mnarewec** [comment]
Incident status should not be a required fields. and I believe its should be a free text field
![image](https://cloud.githubusercontent.com/assets/10192106/10884107/e37b1048-81c1-11e5-94c0-638cf6ff9fb0.png)

**Comment by mnarewec** [comment]
Got this run time error when trying to save.
![image](https://cloud.githubusercontent.com/assets/10192106/10987977/fee971ca-8483-11e5-91ef-56bbd56b0c82.png)

**Comment by mnarewec** [comment]
This issue is resolved.
