### ISSUE TITLE
Setup >> Manage Staff. Some New Fields and changes to fields requirements

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#176]
1. Hide the Occupation Type Field.
2. Telephone Number and Location should not be required fields.
2. There three new fields
a. Is a Driver - when checked it should show the driver/license information
b. Is a Mechanic - (A mechanic can also be a driver)
c. Position Number (alpha numeric)

**Comment by agilecubeteam** [comment]
@mnarewec 

Already this page has position field . It's position number ?

**Comment by mnarewec** [comment]
Yes we require position number ..still alpha numeric Field

**Comment by agilecubeteam** [comment]
In staff , Center dropdown is mandatory, should i remove required field from it also , as it is not saved in Database and value is based on Location.

**Comment by mnarewec** [comment]
@agilecubeteam ,no leave it, center let it be required but remove location .

**Comment by mnarewec** [comment]
This issue is closed
