### ISSUE TITLE
Setup >>Asset Type. There is no Asset Sub Category

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#18]
![image](https://cloud.githubusercontent.com/assets/10192106/8972894/e874a78c-36a1-11e5-9cb1-aaf60adb5335.png)

**Comment by agilecube** [comment]
Sub-category management is not there in site-map. Do let us know if this needs to be implemented.

**Comment by mnarewec** [comment]
Please check PAMS Categories..Its there.

**Comment by mnarewec** [comment]
this been resolved.
