### ISSUE TITLE
System Setup >> Manage Alerts. Please refresh my memory regarding different types of alerts

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#190]
How may different types of alerts should we have. I think we should have
1. Accommodation Alert - That's to send the Building Accommodation Application 
2. Maintenance Alert - That's to send Request for Building Maintenance 
3. Service Alerts - That's to send Vehicle Schedule Service notice
4. Registration Alerts - That's to send Registration Expiry notice
5. Safety Sticker Alerts - That's to send Safety Sticker Expiry alerts.

![image](https://cloud.githubusercontent.com/assets/10192106/10867836/90518216-80c3-11e5-81ea-e68f293c8b28.png)

**Comment by agilecubeteam** [comment]
@mnarewec 

Yes

**Comment by mnarewec** [comment]
Ok but only see some alerts in the Alerts setup??
![image](https://cloud.githubusercontent.com/assets/10192106/10937549/3ae412b6-833f-11e5-9321-ce63b81c76f9.png)

**Comment by agilecubeteam** [comment]
@mnarewec 

Please use this script for changes in Db

Insert into [dbo].[MstUserDefineCode] ([UserDefineTypeId],[Code],[Description])
Values (24,'Registration','Registration'),(24,'SafetySticker','SafetySticker')

**Comment by mnarewec** [comment]
Please send me FULL listing of Alert Types.because I might be getting these values incorrect.

**Comment by mnarewec** [comment]
We should be Merging Compliance Type With Alert Types. They are the same thing.

![image](https://cloud.githubusercontent.com/assets/10192106/12845219/30d85200-cc50-11e5-906f-878496f8de47.png)

![image](https://cloud.githubusercontent.com/assets/10192106/12845191/18b71a76-cc50-11e5-8115-d3507550383f.png)

**Comment by mnarewec** [comment]
This is implemented. Thank you.
