### ISSUE TITLE
Building Management >> Maintenance Request >> Alerts not sending out

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#192]
I received email for alerts for Occupation Application but I am not receiving emails for Maintenance Request. Please check and rectify.

**Comment by mnarewec** [comment]
Email sent and able to receive. However refer corrections on the image and rectify.

![image](https://cloud.githubusercontent.com/assets/10192106/10923896/26018f1a-82cf-11e5-8617-b23d843724ac.png)

**Comment by mnarewec** [comment]
1. The link still not working
2. Also like accommodation, put a progress type icon that indicates progressing when saving the request so users can know.

**Comment by agilecubeteam** [comment]
@mnarewec  
Please send me the link you are receiving in the mail.

**Comment by mnarewec** [comment]
http://localhost/fams/webapi/maintenance-request-modify/M20150002

**Comment by mnarewec** [comment]
Unable to test because sending emails is not working.

**Comment by mnarewec** [comment]
Its saving successfully this time but emails where still not sent out

**Comment by mnarewec** [comment]
This has been resolved. Thank you.
