### ISSUE TITLE
Login Screen - Change Logo

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#2]
Replace the current logo with formatted text 'Kumulsoft Fixed Assets' (using font Century Gothic
 Refer attached image as your cue). The background is perfect. Leave it as it is.

![image](https://cloud.githubusercontent.com/assets/10192106/8919331/d3fb8448-3501-11e5-9c3f-bf37a469f6d0.png)

**Comment by agilecube** [comment]
Ok.

**Comment by mnarewec** [comment]
@agilecube 
Please use this image as background  as 'wave'

This is our branding image:
![kumulsoft brand](https://cloud.githubusercontent.com/assets/10192106/9025351/b804dac2-3944-11e5-85ab-f29be088f8ce.png)


And this is our business Card, if our can have the login page to be formatted/layout like this will be great.


![kumulsoft business card](https://cloud.githubusercontent.com/assets/10192106/9025362/531988a0-3945-11e5-94d4-1b7563cfd411.png)

**Comment by agilecube** [comment]
Need high resolution images both images are not able to cover full screen, and stretching does not look good.

**Comment by mnarewec** [comment]
Hi there please refer below this two images
1. https://drive.google.com/file/d/0B9T2hcAcxJgLNmo2UF92WTB6UlE/view?usp=sharing
2. https://drive.google.com/file/d/0B9T2hcAcxJgLY1FnRVJXSDFpOUE/view?usp=sharing

If these two images are still not high resolution then I can get someone to convert it.

**Comment by mnarewec** [comment]
Please include the following text to replace the following : ** Kumulsoft Fixed Assets is a Complete and Integrated Fixed Asset Management Solution**

![image](https://cloud.githubusercontent.com/assets/10192106/10538137/cdce75f4-7439-11e5-9fba-c828305e7077.png)

**Comment by mnarewec** [comment]
Remove the two opening and closing asterisks. Type the text as follows in correct casing:

**Kumulsoft Fixed Asset Management is a complete and integrated Fixed Asset Management Solution**

![image](https://cloud.githubusercontent.com/assets/10192106/10723263/cad093f0-7c04-11e5-862d-9f595f318e00.png)

**Comment by mnarewec** [comment]
This is resolved.
