### ISSUE TITLE
Setup >>Business Units >> Sub Sections

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#20]
User can enter sub-section details at the first page. This will allow user to already selected Wing, Division, and Section and its doing its filtration. This is related to issue #5 

![image](https://cloud.githubusercontent.com/assets/10192106/8973025/4f2033c4-36a3-11e5-9723-c185bf1b2471.png)

**Comment by agilecube** [comment]
Can you please explain what needs to be done?

**Comment by mnarewec** [comment]
I would like to add sub-section in same page and not clicking add and it brings new page, clicking add should make search  row editable for us to add a sub-section and then a save button next to it to save
