### ISSUE TITLE
Changes to Main menu

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#202]
Rename main menu *Asset Registry* to *General Assets Registry* this is so that we are consistent all across.

**Comment by agilecubeteam** [comment]
@mnarewec 
please run this script 

Update Permission set PermissionName='General Assets Registry' , State='General Assets Registry' where  PermissionName='Asset Registry' and State='Asset Registry'

**Comment by mnarewec** [comment]
This is resolved
