### ISSUE TITLE
Building Management >> Manage Occupation >> detail page issues

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#209]
Refer and following corrections.

![image](https://cloud.githubusercontent.com/assets/10192106/10922296/15fbae74-82c6-11e5-97a4-6f87ab067c69.png)

**Comment by agilecubeteam** [comment]
Date of Birth - We restrict user to enter user to set date only before 20 year.

**Comment by mnarewec** [comment]
1. The birthday date control should start at 1997 and back forward i.e. 2015 (Current year) - 18 years old.
2. Notification should say Email send successfully, if emailed is sent. Otherwise put in the appropriate message.
3. When saving, its taking long to send, so there should be some sort of progress bar, etc advising user that system is still trying to send.
4. When modifying application and clicking Save, do not send the email.

**Comment by mnarewec** [comment]
This has been addressed.
