### ISSUE TITLE
Dashboard >> Asset Dashboard

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#211]
1. Client is really impressed with Asset Search :+1:  and Requested couple of changes
2. Remove/Hide the label *Dashboard* on the dashboard - it occupies space.
2. Remove(hide) *Getting Started* Dashboard item
3. Re-arrange Dashboard items as per the image.

![image](https://cloud.githubusercontent.com/assets/10192106/10928432/0a7cedb4-82f4-11e5-8aa2-d7836d626895.png)

2. Reduce the size of the Asset Types dashboard item by renaming columns as
(a). **Asset** [Asset Type], 
(b). **Count** 
(c). **Cost** [Acquired Cost] currency formatted,
(d). **Value** [CurrentValue]

3. The Asset Search should be **wild card** any part of the following fields when entered should bring up the assets
a. Asset Number
b. Description
l. Asset Type
j. Asset Category
c. Registraion Number (Rego Nbr)
d. Centre Name
f. Custodian
g. Suburb
h. Region
j. Division Name
k. Section Name
g. GL Account
l. Cheque Number
k. Payment Reference

4. Fields to display on Asset Search grid
b. All the above searchable fields
c. Acquired Cost
d. Acquired Date

5. Do not wrap the fields in Asset Search Grid, make then overlap/hidden if cannot shown on the column
6. Make the asset number field as a link to the view page of the asset.

**Comment by agilecubeteam** [comment]
@mnarewec  
please verify and update  which field we want to remove. 

![dashboard](https://cloud.githubusercontent.com/assets/14108944/10962010/70e07668-83ba-11e5-8a1d-ef47b7eb6a6a.jpg)

**Comment by mnarewec** [comment]
Remove the following
1. System user
2. Asset Sub Category
3. Is Allocated
4. WING
5. Region
6. Suburb
7. Registration Number
6. Asset Type

**Comment by mnarewec** [comment]
This is perfect. Thanks
