### ISSUE TITLE
General Asset Registry - Details page for all asset types - Re-arrangement

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#218]
Great effort has been done already for the details page. Please make this few adjustments as per the image and I think the page should be ready for data entry.

**Comment by agilecubeteam** [comment]
![assetregistryre-arrangement](https://cloud.githubusercontent.com/assets/14108944/11176215/df2aa40a-8c60-11e5-8b56-5b696b4a4345.png)

**Comment by mnarewec** [comment]
Thanks so much. This has been achieved.
