### ISSUE TITLE
Setup >> Building >> Suburbs.

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#22]
Suburbs  is like this; Region, Centre, Suburbs. There is no such thing as Location, SubLocation and Suburb.

So please check to Location to **Region** and Sub-Location to **Centre**
![image](https://cloud.githubusercontent.com/assets/10192106/8973764/7af853f6-36ac-11e5-89e5-9dd96defe59f.png)

**Comment by agilecube** [comment]
![image](https://cloud.githubusercontent.com/assets/13015900/8980512/1b189dd8-3666-11e5-9df8-63173acb1469.png)

Can you please explain it in context of above image? 
As per requirement document it has Region -> Center -> Location -> Sub Location
Also, We discussed to connect all items with Location & Sub location where it is connected to center.

Suburb is connected to Center hence we moved that connection to Location and Sub-Location.

**Comment by mnarewec** [comment]
@agilecube , suburb is not part of the Physical Structure but its a different structure of its own by using the top two levels of Physical Structure. It is especially used in the 'Land Building Management' to identify the 'public' location of the land or building in that centre or town. Refer attached image
![image](https://cloud.githubusercontent.com/assets/10192106/8985259/ae13f476-3719-11e5-97bc-f5daacebc1af.png)

**Comment by agilecube** [comment]
@mnarewec, can you please update requirement document for above chart?
Also, please help me to understand
"So please check to Location to Region and Sub-Location to Centre"

**Comment by mnarewec** [comment]
I updated the BR document to Kumulsoft FAMS Specs v3.5

Please check email

**Comment by mnarewec** [comment]
This has been resolved.
