### ISSUE TITLE
Land & Building Management- Main Menu. Rename Occupation Request Queue menu name

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#223]
![image](https://cloud.githubusercontent.com/assets/10192106/11521528/b8ea283e-98f8-11e5-9ac5-e41f60d3d793.png)

**Comment by agilecubeteam** [comment]
@mnarewec 

Run this script and issue will be fixed

update [dbo].[Permission] set PermissionName='Accomodation Request Queue' where PermissionName ='Occupation Request Queue'

**Comment by mnarewec** [comment]
I ran the script but it did not work. The menu name did not change.

**Comment by agilecubeteam** [comment]
@mnarewec 
select *  from [dbo].[Permission] where PermissionName ='Occupation Request Queue'

Please run this script and let me know of there is any data

**Comment by mnarewec** [comment]
Sorry this is resolved.
