### ISSUE TITLE
List of Used Objects and Master and security data tables

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#224]
1. Team I require you to review all the db objects and advise where objects are needed for FAMS to function. This will enable me generate the script to create a fresh database for a new client

2. In addition, I also need to know which tables contains the defaults Master data and security data that requires for a fresh new installation.

**Comment by mnarewec** [comment]
Created a new database and tried to access it but its giving run-time error.

**Comment by agilecubeteam** [comment]
@mnarewec 

can we have access to your pc ?

**Comment by mnarewec** [comment]
The same issue is being addressed in #241
