### ISSUE TITLE
Building Management - Setup and Allocate Building Units is showing now data

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#228]
Urgently resolve

![image](https://cloud.githubusercontent.com/assets/10192106/11591027/5d296f8e-9ae0-11e5-839b-f5935def99b6.png)

**Comment by agilecubeteam** [comment]
@mnarewec 
select * from [dbo].[MstBuildingUnit]

run this script and let me know if there is any data in db

**Comment by mnarewec** [comment]
@agilecubeteam , yes there is data.

**Comment by mnarewec** [comment]
This is resolved.
