### ISSUE TITLE
Asset Administration-Manage Depreciation. Multiple selection of assets based on Asset Categories

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#236]
1. In Manage Asset Type, and Manage Asset Category, Manage Asset Sub Category, we captured the depreciation parameters i.e. *Useful Life Span, Depreciation Method,Residual Value and Depreciation Rate* for a purpose and that is to assist calculate Asset depreciate base on these values.

2. Depreciate can ONLY be calculated for FLEET and GENERAL ASSETS. Depreciation is NOT calculated on LAND & BUILDING

3. In Manage Asset Depreciation, multiple asset should be selected base on the filtration of Asset Type, Category and sub category, for depreciation calculation. If asset is filtered by Asset Type, then the depreciation parameters will be from Asset Type, if Asset is further filtered by Category then depreciation parameters will be based on Category and if asset is further filtered by sub category then depreciation parameters will be based on sub category.

4. If multiple assets are selected then Depreciation Parameters will be selected base on point 3 above. If ONLY one asset is selected then the Depreciation Parameters will be based on the selected asset depreciation parameters (i.e. Asset Master).

4. It will be useful also to show the list (asset Number, Description, Division, Section) of selected assets base on the filtration criteria for calculation.

![image](https://cloud.githubusercontent.com/assets/10192106/11613428/ccfcb9a6-9c6b-11e5-8ef5-f6c817d76962.png)

**Comment by agilecubeteam** [comment]
@mnarewec 
As per our discussion, Asset SubCategory will be removed.

**Comment by mnarewec** [comment]
1. Land & Building assets should not be depreciated but their types are shown here
![image](https://cloud.githubusercontent.com/assets/10192106/12706566/d1468a70-c8d3-11e5-9b9b-9dc7c67ebdde.png)

PLEASE REMOVE THESE TWO TYPES

2. Asset Category is not filtered according to selected asset Type

![image](https://cloud.githubusercontent.com/assets/10192106/12706578/fdeda842-c8d3-11e5-9cea-1eb1d899f611.png).

PLEASE CORRECT THIS

3. How can we Select ALL assets under a particular Category to Calculate Depreciation?
![image](https://cloud.githubusercontent.com/assets/10192106/12706595/47eedec0-c8d4-11e5-845b-adcefa28a37f.png)

4. On the grid below please include 'Purchase Date', 'Purchase Cost' and Current Value
![image](https://cloud.githubusercontent.com/assets/10192106/12706604/82988f6c-c8d4-11e5-8a96-33603c6e1d7d.png)

**Comment by mnarewec** [comment]
Asset Depreciation transaction after depreciation

![image](https://cloud.githubusercontent.com/assets/10192106/12915098/6f77679a-cf74-11e5-9471-a5f7542d7837.png)

Asset number not showing on Vehicle Registery
![image](https://cloud.githubusercontent.com/assets/10192106/12915080/45cba726-cf74-11e5-943f-6863f92f4b07.png)

**Comment by mnarewec** [comment]
Core Functionality of these asset has been implemented. I realise now there are some issues especially in design but will discuss separately.
