### ISSUE TITLE
Dashboard-Current Asset Summary. Purchase cost is not accurate and I believe the current

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#237]
This is the dashboard image
![image](https://cloud.githubusercontent.com/assets/10192106/11620565/c4d9cad6-9cff-11e5-8a11-2ca0d88d3d4d.png)

This is my SQL calculation
![image](https://cloud.githubusercontent.com/assets/10192106/11620621/37362a16-9d00-11e5-8636-6c1cf6297df0.png)

**Comment by agilecubeteam** [comment]
@mnarewec  

cost is calculated only for the asset that is allocated

**Comment by mnarewec** [comment]
@agilecubeteam 
No, it should calculate for everything.

**Comment by mnarewec** [comment]
This is resolved.
