### ISSUE TITLE
Setup-Asset Types. System modules - Merge land and building together

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#238]
Please merge land and building together. They both form the 'Land & Building' system module.

![image](https://cloud.githubusercontent.com/assets/10192106/11623280/9bf1dac4-9d17-11e5-8257-f7dcce0d65c6.png)

Land a

**Comment by agilecubeteam** [comment]
@mnarewec  

What has to be done in Product Code? As of now it is having 4 different modules i.e 
1. General Asset 
2. Fleet
3. Building
4. Land
Do i need to change in that also accordingly ?

**Comment by mnarewec** [comment]
@agilecubeteam, yes please

**Comment by agilecubeteam** [comment]
@mnarewec 
at certain places we will need to differentiate between land and building. Now as if we are merging even system module , which was used to differentiate between modules , should I now use AssetTypeName to compare, Like , if i need only Building Values , i would be comparing with "Building" which is AssetTypeName?

**Comment by mnarewec** [comment]
@agilecubeteam, Please dis-regard this issue. I did not realise this. Thank you so much for this query.

DO NOT MERGE.
