### ISSUE TITLE
Land & Building Management Menu

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#239]
Please high the following menu items highlighted. This will be latter used but its confusing because we don't know what it is used for. And rename the menu item circled in red to 'Accommodation Request Queue'

![image](https://cloud.githubusercontent.com/assets/10192106/11624103/2dbe78d6-9d1d-11e5-9f4f-18399f21ea39.png)

**Comment by agilecubeteam** [comment]
@mnarewec  

you can uncheck the above Names you have provided from ManagePermission in Security

**Comment by mnarewec** [comment]
O Ok...thanks @agilecubeteam

**Comment by mnarewec** [comment]
This has been resolved.
