### ISSUE TITLE
Asset Administration - Asset Revaluation - Details Page

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#246]
When Asset is selected for re-valudation, show the Asset Description/Type/Category/ and Acquisition Information like Acquired Date / Acquired Cost, Division,Section, Centre, Location, Custodian 

![image](https://cloud.githubusercontent.com/assets/10192106/11714169/f5f17bf6-9f83-11e5-9cd5-b49bd3eef74a.png)

**Comment by mnarewec** [comment]
Got a runtime error 
![image](https://cloud.githubusercontent.com/assets/10192106/12740071/677d5626-c9bb-11e5-86bb-a28353f0b351.png)

**Comment by agilecubeteam** [comment]
In our side no error occured ? so, Can you say us when you have arise error ?

**Comment by mnarewec** [comment]
Asset Number is not look up and eventhough I entered a asset number it automatically cleared it when I move to another field.
![image](https://cloud.githubusercontent.com/assets/10192106/12913767/61ab7aaa-cf6c-11e5-96b6-492c98713d50.png)

**Comment by mnarewec** [comment]
The core functionality has been achieved but there are issues will outstanding for calculation/accuracy and will be raised in separate issues.
