### ISSUE TITLE
Asset Administration - Asset Revaluation  Calculation not working

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#247]
It seems Asset Revaluation Calculation is not working
![image](https://cloud.githubusercontent.com/assets/10192106/11714208/4f605ed2-9f84-11e5-9189-256cf8815595.png)

**Comment by agilecubeteam** [comment]
@mnarewec 
Please tell me if following calculation is correct ?

![assetrevaluation](https://cloud.githubusercontent.com/assets/14108944/11737137/470bbc7c-9ffc-11e5-8d10-880e1eb9736c.png)

**Comment by mnarewec** [comment]
Yes this calculation is correct.

**Comment by mnarewec** [comment]
This issue is no longer .
