### ISSUE TITLE
Cron Job - Vehicle Safety Sticker

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#256]
1. Cron Job
a. Setup Cron Job to run once daily
b.Send one report per section listing all vehicles in a **Section** that are due for Sticker (Two weeks before due date] to the person setup in **Manage Alert** to receive alert for that section for Vehicle Safety Sticker Renewal Alerts

2. Report for Vehicle Due For Safety Sticker Renewal
a.  Report fields [Vehicle Rego, Description, Make, Model, Custodian, SS Date, SS Expiry]
b. Color those who have less than 7 days for SS in Orange
c. Color those who have more than 7 days but less than 14 days for SS in Yellow
d. Color those who have less than 0 days in RED

**Comment by agilecubeteam** [comment]
SS Expiry =SafetyStickyExpiryDate
then SS Date= ?

**Comment by mnarewec** [comment]
SS issued date.

**Comment by mnarewec** [comment]
Safety Sticker Date

**Comment by mnarewec** [comment]
I have several vehicles whose safety sticker has long over due but i have not received any notification. Please refer image below as an example.

![image](https://cloud.githubusercontent.com/assets/10192106/13245599/12741660-da5a-11e5-8071-56fadc7670d3.png)

**Comment by mnarewec** [comment]
This issue is closed because we are re-designing alerts and notifications platform.
