### ISSUE TITLE
Hide BOS Recommended field from Fleet and General Asset Registry

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#258]
As per our discussion.

**Comment by agilecubeteam** [comment]
@mnarewec 
Run this query in db

delete from [dbo].[MapColumn] where [ColumnName] = 'BOSRecommended' and ModuleName ='Fleet' and ModuleName='GeneralAsset'

**Comment by mnarewec** [comment]
Ok now I am away from office. I will execute that query and advise

**Comment by mnarewec** [comment]
Tried it and it affected no rows.

![image](https://cloud.githubusercontent.com/assets/10192106/12706458/73089a2c-c8d1-11e5-84fa-b7a49b532fe1.png)

**Comment by agilecubeteam** [comment]
Sorry , it's our mistake so, Please try this query

**Comment by mnarewec** [comment]
This is resolved. Thank you.
