### ISSUE TITLE
Issues with Release 2015_12_22

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#259]
1. The database execute script came up with the following errors

![image](https://cloud.githubusercontent.com/assets/10192106/12406153/2c1e658c-be96-11e5-9592-2427f1699fcf.png)

2. The source code release does not have a solution/project file to launch the source code for compilation.
![image](https://cloud.githubusercontent.com/assets/10192106/12406178/6db906e6-be96-11e5-9294-c8ffadba94e9.png)

**Comment by agilecubeteam** [comment]
Source Code uploaded
https://drive.google.com/drive/folders/0ByXcxrXWkGAXWGZPbi1tMXB2Sm8

**Comment by mnarewec** [comment]
The source code issue is resolved but what about the database script error??

**Comment by mnarewec** [comment]
This has been resolved.
