### ISSUE TITLE
Making FAMS Generic

### ISSUE THREAD

**Issue by agilecube** [kumulsoft/Fixed-Assets#27]
On behalf of Kumulsoft: mail dated 14th July 2015
--------------------------------------------------------------------------------
It is our attempt to make this application more generic and can apply to any organisation. Therefore my request to change the rename Business Unit to Department and Cost Centre to Division and new level Section to the Business Unit Structure. In addition to that, we want you to rename ‘Manage Accommodation’, ‘Setup Accommodation’, ‘Allocate Accommodation’  to ‘Manage Building Units’, Setup Building Units’ and ‘Allocate Building Units’. Accommodation Request becomes ‘Occupation Request’.
-Refer V3.1 - Changes are in green

**Comment by mnarewec** [comment]
This has been address
