### ISSUE TITLE
General Asset Register - Status column color should change if different status

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#281]
1. The Active (Green) color is ok
2. The Recommended For Disposal Color (Orange) is not showing. It should show for General Assets Register as well as Vehicle Register

![image](https://cloud.githubusercontent.com/assets/10192106/13143726/9d98ce2e-d691-11e5-9256-9cd48f6334d1.png)

**Comment by agilecubeteam** [comment]
We are displaying record in Grid which have Status 'Active' So, Other Status Record Is not displaying.

**Comment by agilecubeteam** [comment]
In General Asset Registry and everywhere else (except disposed asset listing report) you should show Asset with Status=1 and Status=2   

as per the google talk discussion

**Comment by mnarewec** [comment]
This is issue is resolved.
