### ISSUE TITLE
Land & Building Mgt - Building Maintenance Request Enhancement

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#283]
1. Hide the Remarks Field to save space for Request Detail text box
2. Make the Request Detail Text box to be multiple lines.
3. Rename Building Number to 'Land/Building Number'. The DDL now should list both Land and Building Numbers for selection. If Land is selected, there is no need for Building Unit.
4. Land/Building number should Only be filtered by a Centre and Suburb DLL, there is no need for Division, section and sub-section filtration. So Remove Division, Section, sub-section DLL
5. For selected then display the following fields ; Land Type, Category, Ownership, Centre, Suburb, Section, Lot, Property Category, Tenants (if Building unit is occupied)

![960281aa-d970-11e5-9dc5-b0243c1330a0](https://cloud.githubusercontent.com/assets/10192106/13209865/ec597eba-d974-11e5-9d63-87c2509351ad.png)

**Comment by agilecubeteam** [comment]
@mnarewec 
Above Point - 5  :  Can you say me which Property Category ?

**Comment by mnarewec** [comment]
Instead of Property Category use 'Land Category'

**Comment by mnarewec** [comment]
Please refer image below make following corrections especially when a building unit is selected.
1. Show ownership value - its not showing
2. Section should be 'Sec' - show 'Sec' value
3. Show lot value - its not showing
4. Show tenant name if Building unit is occupied


![image](https://cloud.githubusercontent.com/assets/10192106/13559208/1c57b99a-e45d-11e5-8be9-5dae2e62601b.png)

**Comment by mnarewec** [comment]
This is resolved.
