### ISSUE TITLE
Cron Job - Provide explain on how cron Job operates

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#286]
1. Provide flowchart on original logic of each job
2. I need a flowchart of how cron job triggers and works in system

**Comment by agilecubeteam** [comment]
flowchart for vehicle Registration Expiry 
![vehicle registration](https://cloud.githubusercontent.com/assets/14108944/13245667/b59777e0-da34-11e5-8085-e8dfd1143e86.png)

**Comment by agilecubeteam** [comment]
[Cron Job Execution.pdf](https://github.com/kumulsoft/Fixed-Assets/files/144491/Cron.Job.Execution.pdf)


Cron Job Execution Steps and Flow Charts

**Comment by mnarewec** [comment]
This is very detail. Thank you.
