### ISSUE TITLE
Asset Audit Enhancements of Details Page

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#287]
1. I realized a mistake that I think I made and would like to correct it. If a user select the condition 'Recommended For Disposal' this should NOT change the Asset Status in MstAsset, rather if the user CHECKED the Recommended for Disposal checkbox, then it should change the Status in MstAsset.
![image](https://cloud.githubusercontent.com/assets/10192106/13231683/c04ba910-d9f6-11e5-8cfe-c03786b680b9.png)

2. Reflect Point 1 above in Cron Job for Asset Disposal

3. Removed 'Recommended For Disposal' in UDC

4. When Asset Number is selected the please display its read only fields like Description, Type, Category, Asset, Centre, Section, Acquired Date, Acquired Cost, Custodian

5. Rename label Staff to 'Custodian'.

**Comment by agilecubeteam** [comment]
We have already  done in issue #248
5. For Fleet related assets it will search for assets which have exceeded their Useful Life Span or exceeded their Useful mileage and it will set their Status=2 i.e. Recommended for Disposal
6. For General Assets it will search for assets which have exceeded their Useful Life Span and it will set their status=2 i.e. Recommended for Disposal

But we can't understand in point 2 what is reflect in  Cron Job for Asset Disposal

**Comment by mnarewec** [comment]
I have made my response above.

**Comment by mnarewec** [comment]
Excellent. This is resolved.
