### ISSUE TITLE
Level Changes

### ISSUE THREAD

**Issue by agilecube** [kumulsoft/Fixed-Assets#29]
On behalf of Kumulsoft: mail dated 14th July 2015 : Version 3.2 : Page 9-10
-----------------------------------------------------------------------------------------------------------------
2.	We need a one more level down for both Business Units and Physical Location Structure, name it 'Sub-Section' and ' Sub Location' respectively. 
a.	They will not be mandatory fields in data input 
b.	They should have system parameters to whatever labels they wish too but the defaults will be 'Sub Section' and 'Sub Location' 
c.	There should be a system parameter of to determine whether the organisation will use 3 Levels or 4 levels of reporting. If 3 levels then they should not be shown on the reports, report filter or the page (both detail and browse). If 4 levels down then they should be shown on reports, report filter and on the page (browse/detail).

Figure 1 BUSINESS UNITS STRUCTURE

![image](https://cloud.githubusercontent.com/assets/13015900/9194826/bf056ef6-403b-11e5-95c4-786857414173.png)

Figure 2 PHYSICAL LOCATION STRUCTURE

![image](https://cloud.githubusercontent.com/assets/13015900/9194835/ce464f0c-403b-11e5-8271-28231a869798.png)

**Comment by mnarewec** [comment]
This been addressed.
