### ISSUE TITLE
Import Utility - Stage 5 Posting

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#290]
When posting Asset Amount =Transaction Amount = Asset Value

![image](https://cloud.githubusercontent.com/assets/10192106/13234281/92919748-da03-11e5-829d-3e0fc8c2b546.png)

**Comment by agilecubeteam** [comment]
if   Asset Amount =Transaction Amount = Asset Value

![image](https://cloud.githubusercontent.com/assets/14108944/13243353/245fe4c0-da24-11e5-912c-ce9252c6c932.png)

why we need to capture again at Single Operation and in Different field "AssetAmount" ?

**Comment by mnarewec** [comment]
When posting it is a requirement that if the Transaction Type is PURCHASE, CONSTRUCTION or IMPROVEMENT, the Asset Amount should populate the Transaction Amount and Asset Value fields of Asset Transactions table

![image](https://cloud.githubusercontent.com/assets/10192106/13244733/3cb4e6e4-da54-11e5-9f31-a01a3c43fddd.png)

**Comment by mnarewec** [comment]
This issue is closed but its other related issue is raised in #297
