### ISSUE TITLE
Menu Layout - Change in to the currency Kumulsoft Billing System format

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#3]
We feel that the current menu as it is will give users the notion that it is a web site. We want to give the users the notion that it is an database application. Additionally, we want to maintain consistency with our current software Kumulsoft Billing.

We would like the current layout change to meet Kumulsoft Billing Layout
** The Logo to be replaced by the Client Name (Capturing Client Information will be a new requirement)
** Move main menu app so they align with the client name
**  Take the cue from Kumulsoft Billing Menu structure, layout, format and incorporate. Contact me for Team View Demo, I also gave you source code 

1. Menu with horizon sub-items
![image](https://cloud.githubusercontent.com/assets/10192106/8919545/9bd9cf28-3503-11e5-853e-04b3bcabfa18.png)

2. Menu with Widgets links as sub-items
![image](https://cloud.githubusercontent.com/assets/10192106/8919575/d9057532-3503-11e5-925f-dc50ef8ea82f.png)

**Comment by agilecube** [comment]
For Agilecube dev team: Take menu from KBS ( Billing system )

If there is 3 level, the second and third level will be on content area
if there is only 2 level - it will be as sub-menu ( horizontal )

For example: If menu is "System Setup". On click of system setup entire menu will be on content area like fig-2 above. 

For Building Management - Menu will be like Fig-1.

**Comment by mnarewec** [comment]
This has been implemented.
