### ISSUE TITLE
Fleet Compliance - Vehicle Registration

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#304]
1. The Compliance type should be hard coded to 'Registration' and make it read-only
2. When sending email and when its processing in the back ground, there should be an indicator like when saving Accommodation Request 

![image](https://cloud.githubusercontent.com/assets/10192106/13312491/c54aca70-dbe2-11e5-9e71-6130212395bd.png)

**Comment by agilecubeteam** [comment]
@mnarewec  We are not getting Point  - 2. So, Please Describe with us.

**Comment by mnarewec** [comment]
This is resolved. thank you.
