### ISSUE TITLE
Merge Asset Allocation with Vehicle Allocation

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#31]
![image](https://cloud.githubusercontent.com/assets/10192106/9222947/3bd56b9a-4139-11e5-9ec0-80679dabb45e.png)

Note.
1. There is no need now to upgrade Vehicle Allocation. Please re-calculated Hours

**Comment by agilecubeteam** [comment]
As per document v3.6 we need allocation Type. 

Please correct if wrong.

**Comment by mnarewec** [comment]
Will raise again
