### ISSUE TITLE
SETUP - User Define Codes - Update Master Data

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#317]
**Remove the following UD Types and Codes from Master Data**

1. When Appear
2. Severity
3. NotificationType

**Remove the following User Define Codes from Master Data**

1.  All User Define Codes under 'Account Source'
2.

**Comment by agilecubeteam** [comment]
@mnarewec we are using 'Account Source' in Import Data

![1](https://cloud.githubusercontent.com/assets/14108944/13485179/00e9d8e4-e12b-11e5-9b4d-9e779cb2818f.png)

**Comment by mnarewec** [comment]
You are NOT to remove the type  !!!  Just remove the User Define Codes. User will key in or define their own Account Source during setup

**Comment by mnarewec** [comment]
This is resolved
