### ISSUE TITLE
Asset Import - Single Update **RECORD EXISTS** Stage 4

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#327]
Transaction Amount is null

![image](https://cloud.githubusercontent.com/assets/10192106/14007487/00649d2a-f1c3-11e5-9ee6-738a0ad256a8.png)

Maybe because of this
![image](https://cloud.githubusercontent.com/assets/10192106/14007544/6828d034-f1c3-11e5-9dd9-3daedad61fc1.png)

**Comment by agilecubeteam** [comment]
Yes , When Value of  chqAmount is Null then AssetTransaction into TransAmount  is also Set Null.

**Comment by mnarewec** [comment]
ok thank you . this is resolved.
