### ISSUE TITLE
ALL DATA VIEW PAGE - ENABLE PAGING

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#33]
Currently there is no paging and user have to click the scroll bar down (PAMS have paging so it should be implemented here, not necessary the same way. I like the way accounts portal does it and also curent KBS does it)

**Comment by agilecubeteam** [comment]
As per discussion we will go with current structure
As of now system fetches 10 records at a time in continuation till it fetch all records.
