### ISSUE TITLE
All Data Entry Page >> Can we have both the Labels and Entry field on same line?

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#37]
This is to save space and make it more 'neat' and professional like KBS. I am not asking about changing format, but just to have the Field labels and Entry field on the same Line

**Comment by agilecubeteam** [comment]
![withoutvalidation](https://cloud.githubusercontent.com/assets/14108944/9897733/7b02bc1e-5c69-11e5-89ea-8a022377a2e7.jpg)
![withvalidation](https://cloud.githubusercontent.com/assets/14108944/9897734/7b067232-5c69-11e5-9bbd-7dcbeabd1281.jpg)

**Comment by agilecubeteam** [comment]
please verify this Design As soon as possible.

**Comment by mnarewec** [comment]
This looks OK. Please progress with it.

**Comment by mnarewec** [comment]
This looks ok for time being.
