### ISSUE TITLE
DB Changes.

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#39]
1. Move the following field 'LeaseAgreementDetails' from MstBuildingUnit to MstBuildingUnitAllocation
2. Rename the field 'AccommodationType' to 'BuildingUnitType' in table MstBuildingUnit with lookup from UDC
3. Create a new field 'Capacity' (numeric, integer) in table MstBuildingUnit. New Rule : When Allocating Building Units to tenants, the number of tenants it can take is limited to the new field 'Capacity'. You cannot add more than the capacity.

**Comment by agilecubeteam** [comment]
Question: in allocation we are capturing only one tenant

Yes in PAMS but now on..we can add more tenants to a Building Unit..this is especially useful for Students dormitories

Allow user to allocate building multiple time to different tenants based on capacity.

**Comment by agilecubeteam** [comment]
In MstBuildingUnit there is No Field like AccommodationType. 
Do we need to add "BuildingUnitType" in MstBuildingUnit?

**Comment by mnarewec** [comment]
This has been implemented
