### ISSUE TITLE
Asset Balance Sheet Totals is not Correct and Results Duplicating when Filter is applied

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#397]
**1. Total is incorrect (if not filtered). When the report is not filtered it should matched the total of the dashboard item : Asset Summary**

![image](https://cloud.githubusercontent.com/assets/10192106/15197613/c4e3f6f0-1815-11e6-963a-d6376ea4cfb3.png)

**2. Results is duplicating when Filtered is applied**
![image](https://cloud.githubusercontent.com/assets/10192106/15197448/cd1c26ea-1814-11e6-806e-25ca884c3f43.png)

**Comment by agilecubeteam** [comment]
**Fixed Assets Balance Sheet** 
     based on AccountSource and GLAccount
     if AccountSource or GLAccount is null of any asset that asset is not considered for report
 
**Dashboard Assets Summary**
total of all Asset AcquiredCost by AssetType

Note :-  Dashboard Assets Summary and Fixed Assets Balance Sheet grand total  will not match if any asset does not have AccountSource or GLAccount

**Comment by mnarewec** [comment]
@agilecubeteam, your points noted buy **Fixed Assets Balance Sheet** has still have errors

(1) Grand Totals is in correct. I calculate it manually and see the results in the image below
![image](https://cloud.githubusercontent.com/assets/10192106/15263730/e108d238-19af-11e6-97bd-d18ed8799150.png)

(2) Fixed Assets Balance Sheet Grand Total is MORE then the Dashboard Asset Summary. If it is missing some assets due to Account Source and GL Account Not set up, then I guess its totals should be LESS then Dashboard Asset Summary
![image](https://cloud.githubusercontent.com/assets/10192106/15263785/6a5ba6c8-19b0-11e6-819c-ee0ff04366cb.png)

**Comment by mnarewec** [comment]
Please ignore the message above. Your comments are true and will be noted.
