### ISSUE TITLE
Grand Total of Fixed Asset Expenditure Report is in correct

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#398]
Grand Total of Fixed Asset Expenditure Report is in correct. I think it is missing Fixed Assets from Land, Building and Fleet Registries. The **unfiltered (excluding BUS) Grand Total of this report should matched Grand Total of Fixed Assets Balance Sheet and Should Matched the Dashboard Assets Summary.**
![image](https://cloud.githubusercontent.com/assets/10192106/15198067/5f94cd6c-1818-11e6-926d-95d7caa2c621.png)

**Comment by agilecubeteam** [comment]
Fixed Assets Balance Sheet 
	based on  AccountSource and GLAccount
	if  AccountSource or GLAccount is null of any asset that asset is not considered for report
Fixed Asset Expenditure Report
	based on AcquiredCost group by section 
Dashboard Assets Summary
        total of all Asset AcquiredCost by AssetType

Note :-   Fixed Asset Expenditure Report and Dashboard Assets Summary grand total will match but total of Fixed Assets Balance Sheet will not match if any asset does not have  AccountSource or GLAccount

**Comment by mnarewec** [comment]
Noted. This issue is closed.
