### ISSUE TITLE
The Grand Totals of the Two Expenditure Reports must matched

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#399]
The Grand Totals of the two expenditure Reports i.e. **Fixed Asset Expenditure** and **Fixed Asset Expenditure Summary** must matched. Currently they are not matching.

![image](https://cloud.githubusercontent.com/assets/10192106/15198679/2d7865f6-181c-11e6-8f78-07feed1018f1.png)

**Comment by agilecubeteam** [comment]
Fixed Asset Expenditure Summary  is based AcquiredCost and AcquiredDate 

 Fixed Asset Expenditure is based AcquiredCost

 if some asset does not contain Acquired Date then both Report's Grand Total will not match

**Comment by mnarewec** [comment]
Comments noted. I tested it and its true.
