### ISSUE TITLE
Progressing icon/image/pattern

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#4]
Remove the processing icon and replace with a different icon. Also change the location so that it appears at the centre of the page like other applications.

![image](https://cloud.githubusercontent.com/assets/10192106/8919638/739a67c4-3504-11e5-9bbc-f8a7452e3cad.png)

I prefer this processing icon
![image](https://cloud.githubusercontent.com/assets/10192106/8919724/2a7c462e-3505-11e5-982c-548ff33ab221.png)

**Comment by agilecube** [comment]
Ok

**Comment by mnarewec** [comment]
This has been implemented.
