### ISSUE TITLE
Setup>>Home Page . Correction to section/menu names

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#40]
1. Rename section General Assets to 'Asset Categories'
2. Rename Management Structure to 'Business Units'
3. Rename Manage Location1 to 'Manage Location'
4. Rename section Vehicle to 'Fleet'
5. Rename 'Manage Asset SubCategory' to 'Manage Asset Subcategory'
6. Rename 'Manage Asset Categories' to 'Manage Asset Category'
7. When System Parameters name change especially for Business Units and Physical Locations, the menu here should also to reflect this. E.g. We change Department to WING but so the menu item here should be 'Manage WING'

**Comment by agilecubeteam** [comment]
-> Rename Manage Location1 to 'Manage Location'
Location name is from System Configuration. As of now it is configured to Location1.
You can change it from System Configuration menu.

**Comment by mnarewec** [comment]
I can't see system configuration menu

![image](https://cloud.githubusercontent.com/assets/10192106/10420598/df719e10-70da-11e5-94d3-fd94db8c3c51.png)

**Comment by mnarewec** [comment]
This has been resolved.
