### ISSUE TITLE
SETUP >> Asset Brand. New Requirement

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#47]
There is new requirement similar to Model of Fleet. We need to create a similar for Brand in FAMS. This should be place in System section of the Setup main menu with relevant security permissions.

**Comment by agilecubeteam** [comment]
Query:
As per following CR we are suppose to replicate Model structure for Brand.
https://github.com/kumulsoft/Fixed-Assets/issues/47

However in Model we have MakeId as foreign key, do we need MakeId in Brand?

**Comment by agilecubeteam** [comment]
We don't need make because it is now being replaced by Manufacturer, so you will need the manufacturer id from UDC

**Comment by mnarewec** [comment]
closed
