### ISSUE TITLE
Data List View and Data Entry View

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#5]
I have given you the source code of zims. Use its data list view and entry view for this FAMS to organise it so the fields, tables etc appear neat and tidy.

(1) Data List View - Many fields (This data table contain many fields so data entry is happening at the next page)
![image](https://cloud.githubusercontent.com/assets/10192106/8919915/bdb10c4e-3506-11e5-912f-cdf80865f1e1.png)

(2) Data Entry View - Many Fields 
![image](https://cloud.githubusercontent.com/assets/10192106/8919934/fad8fa82-3506-11e5-97c2-664e3bd2adf9.png)

(3) Data Entry and List  - few fields, so data entry and view appears together. You will apply this especially to setup components.

![image](https://cloud.githubusercontent.com/assets/10192106/8919968/371ff48c-3507-11e5-889f-9de78df800fd.png)

**Comment by agilecube** [comment]
Marsh, is it possible for you to define no of fields, like if two field,or if three fields take to same page or different page. If that is difficult, let's define page wise what to do. Please suggest.

**Comment by mnarewec** [comment]
Seven or less fields.

 

Cheers!

 

Marsh Narewec

Kumulsoft

**Comment by agilecube** [comment]
Marsh, As per our discussion, we are going to take theme of KBS. so, view/list will be as per KBS and not as per ZIMS. Please let me know if any change.

**Comment by mnarewec** [comment]
ok noted.
