### ISSUE TITLE
SETUP >> System Parameters . Accommodation Label

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#50]
Please advice if this requirement has been implemented.
![image](https://cloud.githubusercontent.com/assets/10192106/9646379/575a5324-5216-11e5-8fde-e9228470b2f9.png)

**Comment by agilecubeteam** [comment]
As per discussion as of now it is hidden from system.

**Comment by mnarewec** [comment]
This is closed. will be raised separately.
