### ISSUE TITLE
Security >> User Management. IsLogin reporting incorrect

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#54]
Look at the image below. These users are not login into the system but it is showing the IsLogin status as True. Only the Administrator is login but its IsLogin status is False. Quiet the opposite. Please rectify
![image](https://cloud.githubusercontent.com/assets/10192106/9667686/99366c10-52c0-11e5-9977-dba3f4d43ec8.png)

**Comment by mnarewec** [comment]
Administrator is login but its still showing false

**Comment by agilecubeteam** [comment]
This is working fine at our end. can you show us on your machine?

**Comment by mnarewec** [comment]
This is resolved.
