### ISSUE TITLE
Organise and save space.

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#6]
1. Rows Size spacing - Organise spacing so that it much not be so much space but sufficient. The idea is to see as much content on one page as much as possible but not to affect the presentation. Please take cue from ZIMS or KBS

2. The current font size is ok but it can be reduce or change to a different font to reduce it. Again take cue from ZIMS or KBS.

**Comment by agilecube** [comment]
Can we take the theme from ZIMS or KBS ? Let me know your selection. We shall replace entire theme. 
To look exactly like those system.

**Comment by mnarewec** [comment]
Take Theme from KBS

**Comment by mnarewec** [comment]
Thanks this has been addressed.
