### ISSUE TITLE
Parameters to show certain fields on respective Registry

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#67]
I though we approve a CR to  map fields on respective registry page? What happened?

**Comment by agilecubeteam** [comment]
@mnarewec, Can you please explain your query?
As of now in asset registry, fields displayed in list and edit page are based on mapping stored in DB.

**Comment by mnarewec** [comment]
Which db table holds the mapping?

**Comment by agilecubeteam** [comment]
MapColumn

**Comment by mnarewec** [comment]
ok thanks and noted.
