### ISSUE TITLE
BIG ISSUE: Page unable to load when Off-line i.e. not connected to Internet

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#68]
Deploy on client machine but found out that the page (Dashboard and menu) etc cannot load if not connected to internet. Tried on my local machine and confirm the problem. Please resolve ASAP.

@agilecubeteam

**Comment by agilecubeteam** [comment]
@mnarewec: you have already raised this issue 
https://github.com/kumulsoft/Fixed-Assets/issues/52
it's not yet fixed.

**Comment by mnarewec** [comment]
ok I will close this.
