### ISSUE TITLE
Report Filters are not Cascading for Locations, Business Units and Categories

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#72]
1. If we select a region, then the corresponding centres should be shown on the centre drop down list
2. if we select a Wind, then the corresponding divisions should be shown on the divisions drop down list
3. if we select a Asset Type, then the corresponding asset categories should be shown on the categories drop down list

This applies to all reports.

**Comment by mnarewec** [comment]
Filters cascading for Business Units and Asset Types working but not the Locations. Please refer below

![image](https://cloud.githubusercontent.com/assets/10192106/10567922/1d56a298-7653-11e5-817b-2f59f4cf5556.png)

**Comment by mnarewec** [comment]
@agilecubeteam, this issue is not resolved yet.

Filters cascading for Business Units and Asset Types working but not the Locations.

Refer above image

**Comment by mnarewec** [comment]
@agilecubeteam , the filter cascading did for Locations now, but the problem is filter is not working for **centre**

**Comment by agilecubeteam** [comment]
@mnarewec 
It's working with center filtration.

**Comment by mnarewec** [comment]
This is resolved.
