### ISSUE TITLE
Reports >> Asset By Business Units (Management Structure

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#75]
**Correct report as per image below**
![image](https://cloud.githubusercontent.com/assets/10192106/10440748/595d6de4-7185-11e5-8b0f-54f73603d14a.png)

**Comment by agilecubeteam** [comment]
Please check and Update .  I can't give more space otherwise format will not look  good. 
![sample 1](https://cloud.githubusercontent.com/assets/14108944/10455667/3c72ef56-71da-11e5-9263-e58202f1ca06.png)

**Comment by mnarewec** [comment]
@agilecubeteam , I have raised a new issue to address this. Will close for meantime.
