### ISSUE TITLE
ALL Reports : Font Style

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#77]
Especially for all PDF Reports, do the following 
1. Change font to 'verdana'
2. The header i.e. Report name should be size 14
3. If there are three levels (groups) then First Level Font size 12 (Uppder Case), Second Level size 11 (Upper case), and third level size 10 (Upper case)
4. Normal font size should be size 9

**Comment by agilecubeteam** [comment]
Please check this and update.
![sample](https://cloud.githubusercontent.com/assets/14108944/10451469/16e73f56-71be-11e5-9ee8-6ce06319d155.PNG)

**Comment by mnarewec** [comment]
@agilecubeteam , I bit my lip again. Please resize all font as per this instruction
1.If there are three levels (groups) then First Level Font size 11 (Uppder Case), Second Level size 10 (Upper case), and third level size 9 (Upper case)
2. Normal font size should be size 7.5

**Comment by mnarewec** [comment]
@agilecubeteam , I've agreed with Nitul with the Font Style. I will wait for your next release to test

**Comment by mnarewec** [comment]
@agilecubeteam , as per my very recent (2015-10-26) gtalk with Nitul, all Font size is reduce to same size irrespective of whether they are 1st level or 2nd level heading,. The font size is 8pt

**Comment by mnarewec** [comment]
@agilecubeteam 
Reports columns especially Asset Purchase cost, does not aligned properly under its header after the change in Report font. Please check and rectify,

**Comment by mnarewec** [comment]
This is resolved.
