### ISSUE TITLE
Export to PDF/Excel resulted in error on Client site

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#82]
**Below is the error message I got from client site** its happen on Client browser. Did not have a chance to test it on Server browser.

![image](https://cloud.githubusercontent.com/assets/10192106/10443957/fa1541a8-71a3-11e5-88de-0656066f99aa.png)

**Comment by agilecubeteam** [comment]
@mnarewec 
Can we get access to that machine? we are not able to re-produce it

**Comment by mnarewec** [comment]
Ok this is just happening to just one client PC. It's working on the others. Will keep it open if the same appears to more than two client pcs.

**Comment by mnarewec** [comment]
This is confirmed alright.
