### ISSUE TITLE
Reports >> Building Registry not working

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#83]
Eventhough there is Building Registry data.

**Building Registry**
![image](https://cloud.githubusercontent.com/assets/10192106/10451386/29913240-71e3-11e5-938d-44ee88c0c477.png)

**Building Registry Report **
![image](https://cloud.githubusercontent.com/assets/10192106/10451398/41b3338c-71e3-11e5-849f-2cf9de53087f.png)

**Comment by agilecubeteam** [comment]
Building Registry Listing Report is based on Suburb, and in the Manage Building , The List does not have any data in   Suburb , Hence data is not displayed in Report.

**Comment by mnarewec** [comment]
I tested by creating suburb and assigning to one  building but that building is not showing on the report.

**Comment by mnarewec** [comment]
This report is now working.
