### ISSUE TITLE
Asset Registry >> Asset Document

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#85]
1. Should browse to select only documents (PDF etc)
2. After document is selected, we are unable to see the doc ???
3. After saving the document, and going in again, its not there
4. When 'viewing' the record, the document is not there?

**Comment by mnarewec** [comment]
@agilecubeteam , this issue still persist. Please rectify.

**Comment by mnarewec** [comment]
Issue still persist.
We are able to save the image/document but when edit/view the record, we cannot download or view the image.

**Comment by mnarewec** [comment]
1. Its storing correctly correctly into the database but when opening its showing a blank document and not the content
2. When accessing document in the View mode, its showing file does not exist error.

**Comment by agilecubeteam** [comment]
@mnarewec can we have access to your machine? this looks working at our end.

**Comment by mnarewec** [comment]
@agilecubeteam Expecting in new release

**Comment by mnarewec** [comment]
Its still showing blank document.

**Comment by agilecubeteam** [comment]
@mnarewec 
can we access your computer for this issue ?

**Comment by mnarewec** [comment]
@agilecubeteam, I am available now

**Comment by mnarewec** [comment]
This issue is resolved. Thanks so much.
