### ISSUE TITLE
Asset Registry >> General Assets Update/View page

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#86]
We need to make that page more user friendly and 'neat' to users. I am suggesting spliting the page into tabs so user can view information on the same page without scrolling and missing information. Here is my suggestions on grouping same fields into section and then into three separate. Please advice if its achievable

![image](https://cloud.githubusercontent.com/assets/10192106/10453553/78d12146-71f0-11e5-8dd9-b230b834ed73.png)

**Comment by agilecubeteam** [comment]
once you updated Menu table with our script, it will start working.

**Comment by mnarewec** [comment]
This is not working after running the script etc !!!

**Comment by agilecubeteam** [comment]
@mnarewec 
This is going to be big change from UI prospective.
As of now we are using same page for Asset Registry for all modules (due to it's dynamism).
Better would be if we finalize UI for all modules first and then make changes in code.

If possible provide us same details for other Modules.

**Comment by mnarewec** [comment]
Ok agree. Will keep it but do not work on it until all issues were addressed.

**Comment by mnarewec** [comment]
I will provide for each Modules

**Comment by mnarewec** [comment]
I believe I have provided for all modules.. And this issue is for General Assets.

**Comment by agilecubeteam** [comment]
what is custodian?

**Comment by mnarewec** [comment]
Custodian, is the staff the asset is ALLOCATED to.

**Comment by mnarewec** [comment]
This is closed. Will raise new issue for the format of General Asset Register.
