### ISSUE TITLE
New Report >> Monthly Asset Expenditure Report Summary

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#88]
Report Format
![image](https://cloud.githubusercontent.com/assets/10192106/10454395/c5d50af0-71f7-11e5-9b86-305b771936c5.png)

The report should look something like this

![img_20151013_221703](https://cloud.githubusercontent.com/assets/10192106/10455417/80070fb2-71fe-11e5-9958-94c258e9a018.jpg)

**Comment by agilecubeteam** [comment]
@mnarewec 

We have some questions

1. Executive Unit  - it's Section Name, correct? 
2. 1101 - it's Section Id, correct?
3. Do we need to Display grand total?
4. Do we need to format all currency just like other reports
5. 114 - is GL account number, correct?
6. Leave Fares - is GL account description, correct?

**Comment by mnarewec** [comment]
@agilecubeteam , report not calculating or showing any data.

Report page view
![image](https://cloud.githubusercontent.com/assets/10192106/10790856/5bbff266-7dd1-11e5-8f22-eb4078166f06.png)


Report PDF export
![image](https://cloud.githubusercontent.com/assets/10192106/10790871/716c2cd8-7dd1-11e5-94a0-701a23d9a214.png)

**Comment by mnarewec** [comment]
This report is still not showing data

**Comment by mnarewec** [comment]
the Account Source and the GL Account are not showing clearly.

 Two options
1. Reduce font for this particular report to very low or
2. Use GL Account Code and Account Source code instead of their names

**Comment by agilecubeteam** [comment]
@mnarewec 
Is it about PDF ?

**Comment by mnarewec** [comment]
1). Remove the number in front of Account Source (Division) and move account source more to the left to give more space
2. Grand totals are printed on each other (overappting), refer image

![image](https://cloud.githubusercontent.com/assets/10192106/11026121/b0711b6e-86f0-11e5-85b7-14fcf4afa01e.png)

**Comment by agilecubeteam** [comment]
@mnarewec 
We Use Total label instead of Grand Total in PDF.

**Comment by mnarewec** [comment]
@agilecubeteam, maybe 
1. Remove the label 'Total' and currency symbol if its going to save space to display the totals

![image](https://cloud.githubusercontent.com/assets/10192106/11432011/5d643092-94f0-11e5-9a94-3ac3489c308b.png)

**Comment by mnarewec** [comment]
This report is completed. Eventhough it did not come out as expected but atlease user can export to excel and format. I am not sure if calculations are correct.
