### ISSUE TITLE
Reports >> Following Reports are showing 'User Management' page instead of reports itself

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#89]
Following Reports are showing 'User Management' page instead of reports itself
1. Asset By Category
2.  Accommodation Registry
3. Maintenance Request Listing
4.  Maintenance Monthly Summary
5. Rentals Montly Summary
6. Rates and Utilities

Please rectify

**Comment by agilecubeteam** [comment]
It's database changes

**Comment by agilecubeteam** [comment]
once you updated Menu table with our script, it will start working.

**Comment by mnarewec** [comment]
@agilecubeteam , Following reports are still showing user management page after the SQL Script Update
1. Asset Disposal Listing

**Comment by agilecubeteam** [comment]
@mnarewec 
Please check if Disposed Assets Listing is working.
All above three are not required. 
You can delete them from [Permission] table

**Comment by mnarewec** [comment]
@agilecubeteam , asset listing is working but it is showing data which it shoudn't.

**Comment by mnarewec** [comment]
All these issues been addressed
