### ISSUE TITLE
Reports >> More fixes Asset Balance Sheet Report

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#93]
1. For Account Source Column, Concatenate Account Source Code + Account Description
2. For GL Account Column, Concatenate GL Account Code + Description
3. The report should be summarised, i.e., for a Account Source, there should be one summary line each GL Account.
4. There should be a Summary (Sum of Purchase Cost) Line for change of Account Source,
5. There should be a GRAND TOTAL end the end of the report.

**Comment by agilecubeteam** [comment]
@mnarewec 
Can you please let us know what needs to be done in point 3?
Please check what we have done and if any changes required do let us know.

**Comment by mnarewec** [comment]
@agilecubeteam point (3) - That is for a account source, there should be one summary line for GL Account. Refer inage below
![image](https://cloud.githubusercontent.com/assets/10192106/10788057/94fdd950-7dc0-11e5-985f-fc7f94f27d8e.png)

point (4)  when Account Source is change, then compute its total like all other reports.

**Comment by mnarewec** [comment]
This issue is closed. There are some minor adjustments but will raise separately.
