### ISSUE TITLE
Reports >> Business Unit Structure not showing any data

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#95]
Obviously there is business units data but its not showing on the report

![image](https://cloud.githubusercontent.com/assets/10192106/10535987/ec6c6d40-742a-11e5-910b-22dbd4a4b944.png)

**Comment by mnarewec** [comment]
This has been resolved.

**Comment by agilecubeteam** [comment]
As per discussion change 
group by Department and Divisions instead of Managers

**Comment by mnarewec** [comment]
What is this ??
![image](https://cloud.githubusercontent.com/assets/10192106/10791243/38e0b742-7dd3-11e5-9273-7a01d5d4734d.png)

**Comment by mnarewec** [comment]
Can we just have three columns???Department, Division, Section, sub-section (depending on parameters).
 The current report is still not clear

**Comment by agilecubeteam** [comment]
@mnarewec 
It is in this format right now (refer the image below), you are asking to remove section groupby and section has to be visible in record only? 

![image](https://cloud.githubusercontent.com/assets/14108944/11501439/215f933a-985a-11e5-91ea-11f8d2e2fafa.png)

**Comment by mnarewec** [comment]
No this is not the correct format. Remove the  totals and just list the the sections under that divisions. You making it look complex but its a simple report.

**Comment by mnarewec** [comment]
This is great. Thanks.
