### ISSUE TITLE
Reports >> Service Monthly Summary Report.Showing wrong data

### ISSUE THREAD

**Issue by mnarewec** [kumulsoft/Fixed-Assets#99]
It should not display any data
![image](https://cloud.githubusercontent.com/assets/10192106/10539319/1a06287e-7442-11e5-8f0c-8795eeccdef4.png)

**Comment by agilecubeteam** [comment]
@mnarewec I guess this report is merged with other report and it does not exist. looks like data issue in menu. 
We will update script with next release to remove it.

**Comment by agilecubeteam** [comment]
Use this Query to alter  Permission table.
delete from [fams].[dbo].[Permission] where [PermissionName]= 'Service Monthly Summary'

**Comment by mnarewec** [comment]
ok, I cannot see this report any more after executing the script.
